version: '2'

run:
  timeout: 5m
  tests: true
  concurrency: 8

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

    - gocritic
    - misspell

    - gosec
    - bodyclose
    - sqlclosecheck

    - gocognit

  exclusions:
    paths:
      - internal/database/models
    rules:
      - path: _test\.go
        linters:
          - gocognit
          - gosec
      # weak random is fine for non-security purposes
      - linters: [gosec]
        text: "G404"
      # http server without timeout is acceptable in this context
      - linters: [gosec]
        text: "G114"
      # directory/file permission checks
      - linters: [gosec]
        text: "G30[1246]"

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.Tx).Rollback
        - (*database/sql.DB).Close

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - commentFormatting

    gocognit:
      min-complexity: 20

    misspell: {}
