// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_problems.sql

package sqlcdb

import (
	"context"
)

const addGameProblem = `-- name: AddGameProblem :exec
INSERT INTO game_problems (game_id, problem_index, problem_id, problem_version_id)
VALUES ($1, $2, $3, $4)
`

type AddGameProblemParams struct {
	GameID           int32  `json:"game_id"`
	ProblemIndex     int32  `json:"problem_index"`
	ProblemID        string `json:"problem_id"`
	ProblemVersionID int64  `json:"problem_version_id"`
}

func (q *Queries) AddGameProblem(ctx context.Context, arg AddGameProblemParams) error {
	_, err := q.db.Exec(ctx, addGameProblem,
		arg.GameID,
		arg.ProblemIndex,
		arg.ProblemID,
		arg.ProblemVersionID,
	)
	return err
}

const countGameProblems = `-- name: CountGameProblems :one
SELECT count(*)
FROM game_problems
WHERE game_id = $1
`

func (q *Queries) CountGameProblems(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGameProblems, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGameProblemByIndex = `-- name: GetGameProblemByIndex :one
SELECT gp.problem_id, gp.problem_version_id, pv.artifact_path
FROM game_problems gp
JOIN problem_versions pv ON pv.id = gp.problem_version_id
WHERE gp.game_id = $1 AND gp.problem_index = $2
LIMIT 1
`

type GetGameProblemByIndexParams struct {
	GameID       int32 `json:"game_id"`
	ProblemIndex int32 `json:"problem_index"`
}

type GetGameProblemByIndexRow struct {
	ProblemID        string `json:"problem_id"`
	ProblemVersionID int64  `json:"problem_version_id"`
	ArtifactPath     string `json:"artifact_path"`
}

func (q *Queries) GetGameProblemByIndex(ctx context.Context, arg GetGameProblemByIndexParams) (GetGameProblemByIndexRow, error) {
	row := q.db.QueryRow(ctx, getGameProblemByIndex, arg.GameID, arg.ProblemIndex)
	var i GetGameProblemByIndexRow
	err := row.Scan(&i.ProblemID, &i.ProblemVersionID, &i.ArtifactPath)
	return i, err
}

const getGameProblemIDByIndex = `-- name: GetGameProblemIDByIndex :one
SELECT problem_id
FROM game_problems
WHERE game_id = $1 AND problem_index = $2
LIMIT 1
`

type GetGameProblemIDByIndexParams struct {
	GameID       int32 `json:"game_id"`
	ProblemIndex int32 `json:"problem_index"`
}

func (q *Queries) GetGameProblemIDByIndex(ctx context.Context, arg GetGameProblemIDByIndexParams) (string, error) {
	row := q.db.QueryRow(ctx, getGameProblemIDByIndex, arg.GameID, arg.ProblemIndex)
	var problem_id string
	err := row.Scan(&problem_id)
	return problem_id, err
}

const getGameProblemIDs = `-- name: GetGameProblemIDs :many
SELECT problem_id
FROM game_problems
WHERE game_id = $1
ORDER BY problem_index
`

func (q *Queries) GetGameProblemIDs(ctx context.Context, gameID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getGameProblemIDs, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var problem_id string
		if err := rows.Scan(&problem_id); err != nil {
			return nil, err
		}
		items = append(items, problem_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameProblemIDsByGameIDs = `-- name: GetGameProblemIDsByGameIDs :many
SELECT game_id, problem_id
FROM game_problems
WHERE game_id = ANY($1::int[])
ORDER BY game_id, problem_index
`

type GetGameProblemIDsByGameIDsRow struct {
	GameID    int32  `json:"game_id"`
	ProblemID string `json:"problem_id"`
}

func (q *Queries) GetGameProblemIDsByGameIDs(ctx context.Context, dollar_1 []int32) ([]GetGameProblemIDsByGameIDsRow, error) {
	rows, err := q.db.Query(ctx, getGameProblemIDsByGameIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGameProblemIDsByGameIDsRow{}
	for rows.Next() {
		var i GetGameProblemIDsByGameIDsRow
		if err := rows.Scan(&i.GameID, &i.ProblemID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
