// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_participants.sql

package sqlcdb

import (
	"context"
)

const addGameParticipant = `-- name: AddGameParticipant :exec
INSERT INTO game_participants (game_id, user_id)
VALUES ($1, $2)
`

type AddGameParticipantParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) error {
	_, err := q.db.Exec(ctx, addGameParticipant, arg.GameID, arg.UserID)
	return err
}

const isGameParticipant = `-- name: IsGameParticipant :one
SELECT EXISTS(
    SELECT 1 FROM game_participants
    WHERE game_id = $1 AND user_id = $2
) AS is_participant
`

type IsGameParticipantParams struct {
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) IsGameParticipant(ctx context.Context, arg IsGameParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGameParticipant, arg.GameID, arg.UserID)
	var is_participant bool
	err := row.Scan(&is_participant)
	return is_participant, err
}
