// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
)

const cancelGame = `-- name: CancelGame :one
UPDATE games
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token
`

func (q *Queries) CancelGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, cancelGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const completeGame = `-- name: CompleteGame :one
UPDATE games
SET status = 'finished',
    winner_id = $2,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token
`

type CompleteGameParams struct {
	ID       int32         `json:"id"`
	WinnerID uuid.NullUUID `json:"winner_id"`
}

func (q *Queries) CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, completeGame, arg.ID, arg.WinnerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const countGamesForUser = `-- name: CountGamesForUser :one
SELECT count(*) FROM games
WHERE is_public = true
   OR creator_id = $1::uuid
   OR EXISTS (
       SELECT 1 FROM game_participants
       WHERE game_id = games.id AND user_id = $1::uuid
   )
`

func (q *Queries) CountGamesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGamesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (creator_id, status, is_public)
VALUES ($1, 'pending', $2)
RETURNING id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token
`

type CreateGameParams struct {
	CreatorID uuid.UUID `json:"creator_id"`
	IsPublic  bool      `json:"is_public"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.CreatorID, arg.IsPublic)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :execrows
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGame, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token FROM games WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGameByID(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const getGameByInviteToken = `-- name: GetGameByInviteToken :one
SELECT id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token FROM games WHERE invite_token = $1 LIMIT 1
`

func (q *Queries) GetGameByInviteToken(ctx context.Context, inviteToken uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByInviteToken, inviteToken)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const getGameForUpdate = `-- name: GetGameForUpdate :one
SELECT id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token FROM games WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetGameForUpdate(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGameForUpdate, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const listGamesForUser = `-- name: ListGamesForUser :many
SELECT id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token FROM games
WHERE is_public = true
   OR creator_id = $3::uuid
   OR EXISTS (
       SELECT 1 FROM game_participants
       WHERE game_id = games.id AND user_id = $3::uuid
   )
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListGamesForUserParams struct {
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListGamesForUser(ctx context.Context, arg ListGamesForUserParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesForUser, arg.Limit, arg.Offset, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.WinnerID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublic,
			&i.InviteToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'active',
    started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, creator_id, winner_id, status, started_at, completed_at, created_at, updated_at, is_public, invite_token
`

func (q *Queries) StartGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.InviteToken,
	)
	return i, err
}

const updateGameWinner = `-- name: UpdateGameWinner :exec
UPDATE games SET winner_id = $2, updated_at = NOW() WHERE id = $1
`

type UpdateGameWinnerParams struct {
	ID       int32         `json:"id"`
	WinnerID uuid.NullUUID `json:"winner_id"`
}

func (q *Queries) UpdateGameWinner(ctx context.Context, arg UpdateGameWinnerParams) error {
	_, err := q.db.Exec(ctx, updateGameWinner, arg.ID, arg.WinnerID)
	return err
}
