// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelGame = `-- name: CancelGame :one
UPDATE games
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
RETURNING id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at
`

func (q *Queries) CancelGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, cancelGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeGame = `-- name: CompleteGame :one
UPDATE games
SET status = 'finished',
    winner_id = $2,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at
`

type CompleteGameParams struct {
	ID       int32       `json:"id"`
	WinnerID pgtype.Int4 `json:"winner_id"`
}

func (q *Queries) CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, completeGame, arg.ID, arg.WinnerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countGames = `-- name: CountGames :one
SELECT count(*) FROM games
`

func (q *Queries) CountGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (problem_id, status)
VALUES ($1, 'pending')
RETURNING id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at
`

func (q *Queries) CreateGame(ctx context.Context, problemID int32) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, problemID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :execrows
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGame, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at FROM games WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGameByID(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameForUpdate = `-- name: GetGameForUpdate :one
SELECT id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at FROM games WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetGameForUpdate(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGameForUpdate, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at FROM games ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListGamesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.WinnerID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'active',
    started_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, problem_id, winner_id, status, started_at, completed_at, created_at, updated_at
`

func (q *Queries) StartGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.WinnerID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
