// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID          int32              `json:"id"`
	ProblemID   int32              `json:"problem_id"`
	WinnerID    pgtype.Int4        `json:"winner_id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GameParticipant struct {
	ID     int32 `json:"id"`
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

type Problem struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Difficulty  string             `json:"difficulty"`
	TimeLimit   int32              `json:"time_limit"`
	MemoryLimit int32              `json:"memory_limit"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Solution struct {
	ID            int32              `json:"id"`
	UserID        int32              `json:"user_id"`
	ProblemID     int32              `json:"problem_id"`
	GameID        pgtype.Int4        `json:"game_id"`
	Code          string             `json:"code"`
	Language      string             `json:"language"`
	Status        string             `json:"status"`
	ExecutionTime pgtype.Int4        `json:"execution_time"`
	MemoryUsed    pgtype.Int4        `json:"memory_used"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Rating       pgtype.Int4        `json:"rating"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
