// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationCode struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int32              `json:"attempts"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID          int32              `json:"id"`
	ProblemID   string             `json:"problem_id"`
	WinnerID    pgtype.Int4        `json:"winner_id"`
	Status      string             `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GameParticipant struct {
	ID     int32 `json:"id"`
	GameID int32 `json:"game_id"`
	UserID int32 `json:"user_id"`
}

type Session struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Solution struct {
	ID            int32              `json:"id"`
	UserID        int32              `json:"user_id"`
	ProblemID     string             `json:"problem_id"`
	GameID        pgtype.Int4        `json:"game_id"`
	Code          string             `json:"code"`
	Language      string             `json:"language"`
	Status        string             `json:"status"`
	ExecutionTime pgtype.Int4        `json:"execution_time"`
	MemoryUsed    pgtype.Int4        `json:"memory_used"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	Rating        pgtype.Int4        `json:"rating"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	EmailVerified bool               `json:"email_verified"`
}
