// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problem_versions.sql

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
)

const countProblemVersions = `-- name: CountProblemVersions :one
SELECT COUNT(*) FROM problem_versions WHERE problem_id = $1
`

func (q *Queries) CountProblemVersions(ctx context.Context, problemID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProblemVersions, problemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblemVersion = `-- name: CreateProblemVersion :one
INSERT INTO problem_versions (
    problem_id,
    version,
    artifact_path,
    artifact_sha256,
    limits_time_ms,
    limits_memory_kb,
    checker_type,
    reference_language,
    created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, problem_id, version, artifact_path, artifact_sha256, limits_time_ms, limits_memory_kb, checker_type, reference_language, created_by_user_id, created_at
`

type CreateProblemVersionParams struct {
	ProblemID         int64         `json:"problem_id"`
	Version           int32         `json:"version"`
	ArtifactPath      string        `json:"artifact_path"`
	ArtifactSha256    string        `json:"artifact_sha256"`
	LimitsTimeMs      int32         `json:"limits_time_ms"`
	LimitsMemoryKb    int32         `json:"limits_memory_kb"`
	CheckerType       string        `json:"checker_type"`
	ReferenceLanguage string        `json:"reference_language"`
	CreatedByUserID   uuid.NullUUID `json:"created_by_user_id"`
}

func (q *Queries) CreateProblemVersion(ctx context.Context, arg CreateProblemVersionParams) (ProblemVersion, error) {
	row := q.db.QueryRow(ctx, createProblemVersion,
		arg.ProblemID,
		arg.Version,
		arg.ArtifactPath,
		arg.ArtifactSha256,
		arg.LimitsTimeMs,
		arg.LimitsMemoryKb,
		arg.CheckerType,
		arg.ReferenceLanguage,
		arg.CreatedByUserID,
	)
	var i ProblemVersion
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.Version,
		&i.ArtifactPath,
		&i.ArtifactSha256,
		&i.LimitsTimeMs,
		&i.LimitsMemoryKb,
		&i.CheckerType,
		&i.ReferenceLanguage,
		&i.CreatedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxProblemVersion = `-- name: GetMaxProblemVersion :one
SELECT COALESCE(MAX(version), 0)::int FROM problem_versions WHERE problem_id = $1
`

func (q *Queries) GetMaxProblemVersion(ctx context.Context, problemID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxProblemVersion, problemID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
