// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) error
	AddGameProblem(ctx context.Context, arg AddGameProblemParams) error
	AdvanceParticipantProblem(ctx context.Context, arg AdvanceParticipantProblemParams) (int32, error)
	CancelGame(ctx context.Context, id int32) (Game, error)
	CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error)
	CountGameParticipants(ctx context.Context, gameID int32) (int64, error)
	CountGameProblems(ctx context.Context, gameID int32) (int64, error)
	CountGamesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateProblemCatalog(ctx context.Context, arg CreateProblemCatalogParams) (Problem, error)
	CreateProblemVersion(ctx context.Context, arg CreateProblemVersionParams) (ProblemVersion, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserByEmail(ctx context.Context, arg CreateUserByEmailParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteGame(ctx context.Context, id int32) (int64, error)
	DeleteSession(ctx context.Context, id int32) (int64, error)
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteVerificationCode(ctx context.Context, email string) error
	GetAllParticipantsProblemIndices(ctx context.Context, gameID int32) ([]GetAllParticipantsProblemIndicesRow, error)
	GetGameByID(ctx context.Context, id int32) (Game, error)
	GetGameByInviteToken(ctx context.Context, inviteToken uuid.UUID) (Game, error)
	GetGameForUpdate(ctx context.Context, id int32) (Game, error)
	GetGameProblemByIndex(ctx context.Context, arg GetGameProblemByIndexParams) (GetGameProblemByIndexRow, error)
	GetGameProblemIDByIndex(ctx context.Context, arg GetGameProblemIDByIndexParams) (string, error)
	GetGameProblemIDs(ctx context.Context, gameID int32) ([]string, error)
	GetGameProblemIDsByGameIDs(ctx context.Context, dollar_1 []int32) ([]GetGameProblemIDsByGameIDsRow, error)
	GetGameSolutions(ctx context.Context, gameID pgtype.Int4) ([]GetGameSolutionsRow, error)
	GetParticipantProblemIndex(ctx context.Context, arg GetParticipantProblemIndexParams) (int32, error)
	GetParticipants(ctx context.Context, gameID int32) ([]GetParticipantsRow, error)
	GetParticipantsByGameIDs(ctx context.Context, dollar_1 []int32) ([]GetParticipantsByGameIDsRow, error)
	GetProblemCatalogBySlug(ctx context.Context, slug string) (Problem, error)
	GetSessionByID(ctx context.Context, id int32) (Session, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVerificationCode(ctx context.Context, email string) (VerificationCode, error)
	IncrementAttemptsIfBelowLimit(ctx context.Context, arg IncrementAttemptsIfBelowLimitParams) (VerificationCode, error)
	InsertSolution(ctx context.Context, arg InsertSolutionParams) error
	IsGameParticipant(ctx context.Context, arg IsGameParticipantParams) (bool, error)
	ListGamesForUser(ctx context.Context, arg ListGamesForUserParams) ([]Game, error)
	ListPublishedPublicProblems(ctx context.Context) ([]Problem, error)
	RemoveGameParticipant(ctx context.Context, arg RemoveGameParticipantParams) (int64, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetProblemCurrentVersion(ctx context.Context, arg SetProblemCurrentVersionParams) error
	StartGame(ctx context.Context, id int32) (Game, error)
	TimeoutGame(ctx context.Context, id int32) (Game, error)
	UpdateGameWinner(ctx context.Context, arg UpdateGameWinnerParams) error
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (Session, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (VerificationCode, error)
}

var _ Querier = (*Queries)(nil)
