// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) error
	CancelGame(ctx context.Context, id int32) (Game, error)
	CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error)
	CountGameParticipants(ctx context.Context, gameID int32) (int64, error)
	CountGames(ctx context.Context) (int64, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserByEmail(ctx context.Context, arg CreateUserByEmailParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteGame(ctx context.Context, id int32) (int64, error)
	DeleteSession(ctx context.Context, id int32) (int64, error)
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteVerificationCode(ctx context.Context, email string) error
	GetGameByID(ctx context.Context, id int32) (Game, error)
	GetGameForUpdate(ctx context.Context, id int32) (Game, error)
	GetParticipantIDs(ctx context.Context, gameID int32) ([]uuid.UUID, error)
	GetParticipantIDsByGameIDs(ctx context.Context, dollar_1 []int32) ([]GetParticipantIDsByGameIDsRow, error)
	GetSessionByID(ctx context.Context, id int32) (Session, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVerificationCode(ctx context.Context, email string) (VerificationCode, error)
	IncrementAttemptsIfBelowLimit(ctx context.Context, arg IncrementAttemptsIfBelowLimitParams) (VerificationCode, error)
	IsGameParticipant(ctx context.Context, arg IsGameParticipantParams) (bool, error)
	ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	StartGame(ctx context.Context, id int32) (Game, error)
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (Session, error)
	UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (VerificationCode, error)
}

var _ Querier = (*Queries)(nil)
