// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) error
	AddGameProblem(ctx context.Context, arg AddGameProblemParams) error
	AdvanceGameProblem(ctx context.Context, arg AdvanceGameProblemParams) (Game, error)
	CancelGame(ctx context.Context, id int32) (Game, error)
	CompleteGame(ctx context.Context, arg CompleteGameParams) (Game, error)
	CountGameParticipants(ctx context.Context, gameID int32) (int64, error)
	CountGameProblems(ctx context.Context, gameID int32) (int64, error)
	CountGames(ctx context.Context) (int64, error)
	CreateGame(ctx context.Context, creatorID uuid.UUID) (Game, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserByEmail(ctx context.Context, arg CreateUserByEmailParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteGame(ctx context.Context, id int32) (int64, error)
	DeleteSession(ctx context.Context, id int32) (int64, error)
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	DeleteVerificationCode(ctx context.Context, email string) error
	GetGameByID(ctx context.Context, id int32) (Game, error)
	GetGameForUpdate(ctx context.Context, id int32) (Game, error)
	GetGameProblemIDByIndex(ctx context.Context, arg GetGameProblemIDByIndexParams) (string, error)
	GetGameProblemIDs(ctx context.Context, gameID int32) ([]string, error)
	GetGameProblemIDsByGameIDs(ctx context.Context, dollar_1 []int32) ([]GetGameProblemIDsByGameIDsRow, error)
	GetParticipants(ctx context.Context, gameID int32) ([]GetParticipantsRow, error)
	GetParticipantsByGameIDs(ctx context.Context, dollar_1 []int32) ([]GetParticipantsByGameIDsRow, error)
	GetSessionByID(ctx context.Context, id int32) (Session, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVerificationCode(ctx context.Context, email string) (VerificationCode, error)
	IncrementAttemptsIfBelowLimit(ctx context.Context, arg IncrementAttemptsIfBelowLimitParams) (VerificationCode, error)
	IsGameParticipant(ctx context.Context, arg IsGameParticipantParams) (bool, error)
	ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error)
	RemoveGameParticipant(ctx context.Context, arg RemoveGameParticipantParams) (int64, error)
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	StartGame(ctx context.Context, id int32) (Game, error)
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (Session, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (VerificationCode, error)
}

var _ Querier = (*Queries)(nil)
