// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: solutions.sql

package sqlcdb

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getGameSolutions = `-- name: GetGameSolutions :many
SELECT
    s.user_id,
    s.problem_id,
    s.code,
    s.language,
    s.created_at,
    u.username,
    u.name
FROM solutions s
JOIN users u ON u.id = s.user_id
WHERE s.game_id = $1 AND s.status = 'passed'
ORDER BY s.created_at
`

type GetGameSolutionsRow struct {
	UserID    uuid.UUID          `json:"user_id"`
	ProblemID string             `json:"problem_id"`
	Code      string             `json:"code"`
	Language  string             `json:"language"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	Name      pgtype.Text        `json:"name"`
}

func (q *Queries) GetGameSolutions(ctx context.Context, gameID pgtype.Int4) ([]GetGameSolutionsRow, error) {
	rows, err := q.db.Query(ctx, getGameSolutions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGameSolutionsRow{}
	for rows.Next() {
		var i GetGameSolutionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ProblemID,
			&i.Code,
			&i.Language,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSolution = `-- name: InsertSolution :exec
INSERT INTO solutions (user_id, problem_id, problem_version_id, game_id, code, language, status)
VALUES ($1, $2, $3, $4, $5, $6, 'passed')
ON CONFLICT (user_id, game_id, problem_id) DO NOTHING
`

type InsertSolutionParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	ProblemID        string      `json:"problem_id"`
	ProblemVersionID pgtype.Int8 `json:"problem_version_id"`
	GameID           pgtype.Int4 `json:"game_id"`
	Code             string      `json:"code"`
	Language         string      `json:"language"`
}

func (q *Queries) InsertSolution(ctx context.Context, arg InsertSolutionParams) error {
	_, err := q.db.Exec(ctx, insertSolution,
		arg.UserID,
		arg.ProblemID,
		arg.ProblemVersionID,
		arg.GameID,
		arg.Code,
		arg.Language,
	)
	return err
}
