// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_codes.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE FROM verification_codes WHERE email = $1
`

func (q *Queries) DeleteVerificationCode(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, email)
	return err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT email, code_hash, expires_at, attempts, created_at FROM verification_codes WHERE email = $1
`

func (q *Queries) GetVerificationCode(ctx context.Context, email string) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, email)
	var i VerificationCode
	err := row.Scan(
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAttemptsIfBelowLimit = `-- name: IncrementAttemptsIfBelowLimit :one
UPDATE verification_codes
SET attempts = attempts + 1
WHERE email = $1 AND attempts < $2
RETURNING email, code_hash, expires_at, attempts, created_at
`

type IncrementAttemptsIfBelowLimitParams struct {
	Email    string `json:"email"`
	Attempts int32  `json:"attempts"`
}

func (q *Queries) IncrementAttemptsIfBelowLimit(ctx context.Context, arg IncrementAttemptsIfBelowLimitParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, incrementAttemptsIfBelowLimit, arg.Email, arg.Attempts)
	var i VerificationCode
	err := row.Scan(
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerificationCode = `-- name: UpsertVerificationCode :one
INSERT INTO verification_codes (email, code_hash, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
    SET code_hash  = EXCLUDED.code_hash,
        expires_at = EXCLUDED.expires_at,
        attempts   = 0
RETURNING email, code_hash, expires_at, attempts, created_at
`

type UpsertVerificationCodeParams struct {
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, upsertVerificationCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	var i VerificationCode
	err := row.Scan(
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}
