// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for GameStatus.
const (
	Active    GameStatus = "active"
	Cancelled GameStatus = "cancelled"
	Finished  GameStatus = "finished"
	Pending   GameStatus = "pending"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	case Finished:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// CompleteGameRequest defines model for CompleteGameRequest.
type CompleteGameRequest struct {
	WinnerId int `json:"winner_id"`
}

// CountResponse defines model for CountResponse.
type CountResponse struct {
	Count int64 `json:"count"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	PlayerIds []int `json:"player_ids"`
	ProblemId int   `json:"problem_id"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	UserId int `json:"user_id"`
}

// DeletedResponse defines model for DeletedResponse.
type DeletedResponse struct {
	Deleted bool `json:"deleted"`
}

// EndedResponse defines model for EndedResponse.
type EndedResponse struct {
	Ended bool `json:"ended"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

// Game defines model for Game.
type Game struct {
	CreatedAt time.Time  `json:"created_at"`
	Id        int        `json:"id"`
	ProblemId int        `json:"problem_id"`
	Status    GameStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
	WinnerId  *int       `json:"winner_id,omitempty"`
}

// GameStatus defines model for Game.Status.
type GameStatus string

// GameResponse defines model for GameResponse.
type GameResponse struct {
	Game Game `json:"game"`
}

// ListGamesResponse defines model for ListGamesResponse.
type ListGamesResponse struct {
	Games []Game `json:"games"`
	Total int64  `json:"total"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Id        int       `json:"id"`
	Token     string    `json:"token"`
	UserId    int       `json:"user_id"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	Session Session `json:"session"`
}

// UserSessionsResponse defines model for UserSessionsResponse.
type UserSessionsResponse struct {
	Sessions []Session `json:"sessions"`
}

// ValidateSessionResponse defines model for ValidateSessionResponse.
type ValidateSessionResponse struct {
	Session Session `json:"session"`
	Valid   bool    `json:"valid"`
}

// GameID defines model for GameID.
type GameID = int

// SessionID defines model for SessionID.
type SessionID = int

// UserID defines model for UserID.
type UserID = int

// Error defines model for Error.
type Error = ErrorResponse

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ValidateSessionParams defines parameters for ValidateSession.
type ValidateSessionParams struct {
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = CreateGameRequest

// CompleteGameJSONRequestBody defines body for CompleteGame for application/json ContentType.
type CompleteGameJSONRequestBody = CompleteGameRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List games with pagination
	// (GET /games)
	ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams)
	// Create a new game
	// (POST /games)
	CreateGame(w http.ResponseWriter, r *http.Request)
	// Delete game by ID
	// (DELETE /games/{id})
	DeleteGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Get game by ID
	// (GET /games/{id})
	GetGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Cancel a game
	// (POST /games/{id}/cancel)
	CancelGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Complete a game with a winner
	// (POST /games/{id}/complete)
	CompleteGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Start a pending game
	// (POST /games/{id}/start)
	StartGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Create a new session
	// (POST /sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Remove all expired sessions
	// (POST /sessions/cleanup)
	CleanupExpiredSessions(w http.ResponseWriter, r *http.Request)
	// Validate a session token
	// (GET /sessions/validate)
	ValidateSession(w http.ResponseWriter, r *http.Request, params ValidateSessionParams)
	// End (delete) a session
	// (DELETE /sessions/{id})
	EndSession(w http.ResponseWriter, r *http.Request, id SessionID)
	// Get session by ID
	// (GET /sessions/{id})
	GetSession(w http.ResponseWriter, r *http.Request, id SessionID)
	// Refresh session expiry
	// (POST /sessions/{id}/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, id SessionID)
	// End all sessions for a user
	// (DELETE /users/{user_id}/sessions)
	EndAllUserSessions(w http.ResponseWriter, r *http.Request, userId UserID)
	// List all sessions for a user
	// (GET /users/{user_id}/sessions)
	GetUserSessions(w http.ResponseWriter, r *http.Request, userId UserID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List games with pagination
// (GET /games)
func (_ Unimplemented) ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new game
// (POST /games)
func (_ Unimplemented) CreateGame(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete game by ID
// (DELETE /games/{id})
func (_ Unimplemented) DeleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game by ID
// (GET /games/{id})
func (_ Unimplemented) GetGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a game
// (POST /games/{id}/cancel)
func (_ Unimplemented) CancelGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complete a game with a winner
// (POST /games/{id}/complete)
func (_ Unimplemented) CompleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a pending game
// (POST /games/{id}/start)
func (_ Unimplemented) StartGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new session
// (POST /sessions)
func (_ Unimplemented) CreateSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove all expired sessions
// (POST /sessions/cleanup)
func (_ Unimplemented) CleanupExpiredSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Validate a session token
// (GET /sessions/validate)
func (_ Unimplemented) ValidateSession(w http.ResponseWriter, r *http.Request, params ValidateSessionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End (delete) a session
// (DELETE /sessions/{id})
func (_ Unimplemented) EndSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get session by ID
// (GET /sessions/{id})
func (_ Unimplemented) GetSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh session expiry
// (POST /sessions/{id}/refresh)
func (_ Unimplemented) RefreshSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End all sessions for a user
// (DELETE /users/{user_id}/sessions)
func (_ Unimplemented) EndAllUserSessions(w http.ResponseWriter, r *http.Request, userId UserID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all sessions for a user
// (GET /users/{user_id}/sessions)
func (_ Unimplemented) GetUserSessions(w http.ResponseWriter, r *http.Request, userId UserID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGame(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGame operation middleware
func (siw *ServerInterfaceWrapper) DeleteGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelGame operation middleware
func (siw *ServerInterfaceWrapper) CancelGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteGame operation middleware
func (siw *ServerInterfaceWrapper) CompleteGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGame operation middleware
func (siw *ServerInterfaceWrapper) StartGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CleanupExpiredSessions operation middleware
func (siw *ServerInterfaceWrapper) CleanupExpiredSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CleanupExpiredSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateSession operation middleware
func (siw *ServerInterfaceWrapper) ValidateSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ValidateSessionParams

	// ------------- Optional query parameter "token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EndSession operation middleware
func (siw *ServerInterfaceWrapper) EndSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EndSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EndAllUserSessions operation middleware
func (siw *ServerInterfaceWrapper) EndAllUserSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EndAllUserSessions(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserSessions operation middleware
func (siw *ServerInterfaceWrapper) GetUserSessions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserSessions(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games", wrapper.ListGames)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games", wrapper.CreateGame)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/games/{id}", wrapper.DeleteGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games/{id}", wrapper.GetGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/cancel", wrapper.CancelGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/complete", wrapper.CompleteGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/start", wrapper.StartGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sessions", wrapper.CreateSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sessions/cleanup", wrapper.CleanupExpiredSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions/validate", wrapper.ValidateSession)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/sessions/{id}", wrapper.EndSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sessions/{id}", wrapper.GetSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sessions/{id}/refresh", wrapper.RefreshSession)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{user_id}/sessions", wrapper.EndAllUserSessions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{user_id}/sessions", wrapper.GetUserSessions)
	})

	return r
}

type ErrorJSONResponse ErrorResponse

type ListGamesRequestObject struct {
	Params ListGamesParams
}

type ListGamesResponseObject interface {
	VisitListGamesResponse(w http.ResponseWriter) error
}

type ListGames200JSONResponse ListGamesResponse

func (response ListGames200JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGames400JSONResponse struct{ ErrorJSONResponse }

func (response ListGames400JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListGames500JSONResponse ErrorResponse

func (response ListGames500JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateGameRequestObject struct {
	Body *CreateGameJSONRequestBody
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse GameResponse

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame400JSONResponse struct{ ErrorJSONResponse }

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame500JSONResponse ErrorResponse

func (response CreateGame500JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGameRequestObject struct {
	Id GameID `json:"id"`
}

type DeleteGameResponseObject interface {
	VisitDeleteGameResponse(w http.ResponseWriter) error
}

type DeleteGame200JSONResponse DeletedResponse

func (response DeleteGame200JSONResponse) VisitDeleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGame404JSONResponse struct{ ErrorJSONResponse }

func (response DeleteGame404JSONResponse) VisitDeleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGame500JSONResponse ErrorResponse

func (response DeleteGame500JSONResponse) VisitDeleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetGameRequestObject struct {
	Id GameID `json:"id"`
}

type GetGameResponseObject interface {
	VisitGetGameResponse(w http.ResponseWriter) error
}

type GetGame200JSONResponse GameResponse

func (response GetGame200JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGame404JSONResponse struct{ ErrorJSONResponse }

func (response GetGame404JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetGame500JSONResponse ErrorResponse

func (response GetGame500JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CancelGameRequestObject struct {
	Id GameID `json:"id"`
}

type CancelGameResponseObject interface {
	VisitCancelGameResponse(w http.ResponseWriter) error
}

type CancelGame200JSONResponse GameResponse

func (response CancelGame200JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelGame400JSONResponse struct{ ErrorJSONResponse }

func (response CancelGame400JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelGame404JSONResponse ErrorResponse

func (response CancelGame404JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelGame500JSONResponse ErrorResponse

func (response CancelGame500JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGameRequestObject struct {
	Id   GameID `json:"id"`
	Body *CompleteGameJSONRequestBody
}

type CompleteGameResponseObject interface {
	VisitCompleteGameResponse(w http.ResponseWriter) error
}

type CompleteGame200JSONResponse GameResponse

func (response CompleteGame200JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGame400JSONResponse struct{ ErrorJSONResponse }

func (response CompleteGame400JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGame404JSONResponse ErrorResponse

func (response CompleteGame404JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGame500JSONResponse ErrorResponse

func (response CompleteGame500JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StartGameRequestObject struct {
	Id GameID `json:"id"`
}

type StartGameResponseObject interface {
	VisitStartGameResponse(w http.ResponseWriter) error
}

type StartGame200JSONResponse GameResponse

func (response StartGame200JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartGame400JSONResponse struct{ ErrorJSONResponse }

func (response StartGame400JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StartGame404JSONResponse ErrorResponse

func (response StartGame404JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartGame500JSONResponse ErrorResponse

func (response StartGame500JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse SessionResponse

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession400JSONResponse struct{ ErrorJSONResponse }

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession500JSONResponse ErrorResponse

func (response CreateSession500JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CleanupExpiredSessionsRequestObject struct {
}

type CleanupExpiredSessionsResponseObject interface {
	VisitCleanupExpiredSessionsResponse(w http.ResponseWriter) error
}

type CleanupExpiredSessions200JSONResponse CountResponse

func (response CleanupExpiredSessions200JSONResponse) VisitCleanupExpiredSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CleanupExpiredSessions500JSONResponse struct{ ErrorJSONResponse }

func (response CleanupExpiredSessions500JSONResponse) VisitCleanupExpiredSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ValidateSessionRequestObject struct {
	Params ValidateSessionParams
}

type ValidateSessionResponseObject interface {
	VisitValidateSessionResponse(w http.ResponseWriter) error
}

type ValidateSession200JSONResponse ValidateSessionResponse

func (response ValidateSession200JSONResponse) VisitValidateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ValidateSession401JSONResponse struct{ ErrorJSONResponse }

func (response ValidateSession401JSONResponse) VisitValidateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ValidateSession500JSONResponse ErrorResponse

func (response ValidateSession500JSONResponse) VisitValidateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EndSessionRequestObject struct {
	Id SessionID `json:"id"`
}

type EndSessionResponseObject interface {
	VisitEndSessionResponse(w http.ResponseWriter) error
}

type EndSession200JSONResponse EndedResponse

func (response EndSession200JSONResponse) VisitEndSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EndSession404JSONResponse struct{ ErrorJSONResponse }

func (response EndSession404JSONResponse) VisitEndSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type EndSession500JSONResponse ErrorResponse

func (response EndSession500JSONResponse) VisitEndSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionRequestObject struct {
	Id SessionID `json:"id"`
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse SessionResponse

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSession404JSONResponse struct{ ErrorJSONResponse }

func (response GetSession404JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSession500JSONResponse ErrorResponse

func (response GetSession500JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RefreshSessionRequestObject struct {
	Id SessionID `json:"id"`
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

type RefreshSession200JSONResponse SessionResponse

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshSession401JSONResponse struct{ ErrorJSONResponse }

func (response RefreshSession401JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshSession404JSONResponse ErrorResponse

func (response RefreshSession404JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RefreshSession500JSONResponse ErrorResponse

func (response RefreshSession500JSONResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type EndAllUserSessionsRequestObject struct {
	UserId UserID `json:"user_id"`
}

type EndAllUserSessionsResponseObject interface {
	VisitEndAllUserSessionsResponse(w http.ResponseWriter) error
}

type EndAllUserSessions200JSONResponse CountResponse

func (response EndAllUserSessions200JSONResponse) VisitEndAllUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type EndAllUserSessions400JSONResponse struct{ ErrorJSONResponse }

func (response EndAllUserSessions400JSONResponse) VisitEndAllUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type EndAllUserSessions500JSONResponse ErrorResponse

func (response EndAllUserSessions500JSONResponse) VisitEndAllUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSessionsRequestObject struct {
	UserId UserID `json:"user_id"`
}

type GetUserSessionsResponseObject interface {
	VisitGetUserSessionsResponse(w http.ResponseWriter) error
}

type GetUserSessions200JSONResponse UserSessionsResponse

func (response GetUserSessions200JSONResponse) VisitGetUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSessions400JSONResponse struct{ ErrorJSONResponse }

func (response GetUserSessions400JSONResponse) VisitGetUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSessions500JSONResponse ErrorResponse

func (response GetUserSessions500JSONResponse) VisitGetUserSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List games with pagination
	// (GET /games)
	ListGames(ctx context.Context, request ListGamesRequestObject) (ListGamesResponseObject, error)
	// Create a new game
	// (POST /games)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Delete game by ID
	// (DELETE /games/{id})
	DeleteGame(ctx context.Context, request DeleteGameRequestObject) (DeleteGameResponseObject, error)
	// Get game by ID
	// (GET /games/{id})
	GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error)
	// Cancel a game
	// (POST /games/{id}/cancel)
	CancelGame(ctx context.Context, request CancelGameRequestObject) (CancelGameResponseObject, error)
	// Complete a game with a winner
	// (POST /games/{id}/complete)
	CompleteGame(ctx context.Context, request CompleteGameRequestObject) (CompleteGameResponseObject, error)
	// Start a pending game
	// (POST /games/{id}/start)
	StartGame(ctx context.Context, request StartGameRequestObject) (StartGameResponseObject, error)
	// Create a new session
	// (POST /sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Remove all expired sessions
	// (POST /sessions/cleanup)
	CleanupExpiredSessions(ctx context.Context, request CleanupExpiredSessionsRequestObject) (CleanupExpiredSessionsResponseObject, error)
	// Validate a session token
	// (GET /sessions/validate)
	ValidateSession(ctx context.Context, request ValidateSessionRequestObject) (ValidateSessionResponseObject, error)
	// End (delete) a session
	// (DELETE /sessions/{id})
	EndSession(ctx context.Context, request EndSessionRequestObject) (EndSessionResponseObject, error)
	// Get session by ID
	// (GET /sessions/{id})
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// Refresh session expiry
	// (POST /sessions/{id}/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// End all sessions for a user
	// (DELETE /users/{user_id}/sessions)
	EndAllUserSessions(ctx context.Context, request EndAllUserSessionsRequestObject) (EndAllUserSessionsResponseObject, error)
	// List all sessions for a user
	// (GET /users/{user_id}/sessions)
	GetUserSessions(ctx context.Context, request GetUserSessionsRequestObject) (GetUserSessionsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListGames operation middleware
func (sh *strictHandler) ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams) {
	var request ListGamesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGames(ctx, request.(ListGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGamesResponseObject); ok {
		if err := validResponse.VisitListGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(w http.ResponseWriter, r *http.Request) {
	var request CreateGameRequestObject

	var body CreateGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteGame operation middleware
func (sh *strictHandler) DeleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request DeleteGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteGame(ctx, request.(DeleteGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteGameResponseObject); ok {
		if err := validResponse.VisitDeleteGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGame operation middleware
func (sh *strictHandler) GetGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request GetGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGame(ctx, request.(GetGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameResponseObject); ok {
		if err := validResponse.VisitGetGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelGame operation middleware
func (sh *strictHandler) CancelGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request CancelGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelGame(ctx, request.(CancelGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelGameResponseObject); ok {
		if err := validResponse.VisitCancelGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteGame operation middleware
func (sh *strictHandler) CompleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request CompleteGameRequestObject

	request.Id = id

	var body CompleteGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteGame(ctx, request.(CompleteGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteGameResponseObject); ok {
		if err := validResponse.VisitCompleteGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGame operation middleware
func (sh *strictHandler) StartGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request StartGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartGame(ctx, request.(StartGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartGameResponseObject); ok {
		if err := validResponse.VisitStartGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CleanupExpiredSessions operation middleware
func (sh *strictHandler) CleanupExpiredSessions(w http.ResponseWriter, r *http.Request) {
	var request CleanupExpiredSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CleanupExpiredSessions(ctx, request.(CleanupExpiredSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CleanupExpiredSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CleanupExpiredSessionsResponseObject); ok {
		if err := validResponse.VisitCleanupExpiredSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ValidateSession operation middleware
func (sh *strictHandler) ValidateSession(w http.ResponseWriter, r *http.Request, params ValidateSessionParams) {
	var request ValidateSessionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ValidateSession(ctx, request.(ValidateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ValidateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ValidateSessionResponseObject); ok {
		if err := validResponse.VisitValidateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EndSession operation middleware
func (sh *strictHandler) EndSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	var request EndSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EndSession(ctx, request.(EndSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EndSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EndSessionResponseObject); ok {
		if err := validResponse.VisitEndSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	var request GetSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	var request RefreshSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx, request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EndAllUserSessions operation middleware
func (sh *strictHandler) EndAllUserSessions(w http.ResponseWriter, r *http.Request, userId UserID) {
	var request EndAllUserSessionsRequestObject

	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EndAllUserSessions(ctx, request.(EndAllUserSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EndAllUserSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EndAllUserSessionsResponseObject); ok {
		if err := validResponse.VisitEndAllUserSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserSessions operation middleware
func (sh *strictHandler) GetUserSessions(w http.ResponseWriter, r *http.Request, userId UserID) {
	var request GetUserSessionsRequestObject

	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserSessions(ctx, request.(GetUserSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserSessionsResponseObject); ok {
		if err := validResponse.VisitGetUserSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa32/bNhD+VwhuDxugxU6b7UFvSeMFAbZ2SNe9BEXASGebnUQqJJXUCPS/D/yh35Rs",
	"t7aa7s0pybvj93083lF9xhFPM86AKYnDZ5wRQVJQIMxfVySF60v9izIc4oyoNQ4wIyngENMYB1jAQ04F",
	"xDhUIocAy2gNKdEr1CYzs5iCFQhcFAF+D1JSzg5o8YMEMWgulyDu9rVZ6Nky40yCgWAhBBf6R8SZAqb0",
	"T5JlCY2IopzNPknO9L/VJn8UsMQh/mFWIzuzo3JmrN04+9ZbDDISNNPGcGjdIVHPKIM1wbzhaZaAAs3L",
	"DTzkIE08meAZCEVtxE+UMbvx8BmnlNE0T3F4Gvjwq4G5baz7WM3l958gUrgI8BueM1VF3nMa6WH9Y8lF",
	"SpR189sZ3urVLvR6FEC2bDVLyMaEbP6iClLpIzXQMFzb0VeVJyIE2ejBTPD7BFKH2JZ4Gy5bK4d34FQ/",
	"uIlSpvuxVa7y+b0ELZJ4mK3YTmhs957zBAjruSln+twsWDzmBPTwDi7sPK+D1mnpO9DDdxGPzRh8Jvpw",
	"4BBfnf+5uHv77u+73999eHtZS1AqQdnKyAGkJKvOshVJATGu0JLnLO4v64Zde68N+nZxZbJR78AYbcR3",
	"pH1qYqLgF0VT8IXtF+g2AQdYKqJyx4lW1y3OgMXaaIBJpOij9rakjMo16I1HhEWQJC1W6ijyLN478lZO",
	"YnmSkHuNuc3GW5RuMnhji9V+giaIrbiGaBjW0sqRNJa8DZHd6MxCn78/qFR6hRx32s5c293305fiiiRf",
	"knqt+9KAbw8udR1GvfA5owLkQRSv+L/AGkMNddbZdBdd1TWCNdkKsyWwEXyGGZY1gGPUljh3QyyX+3zr",
	"0setk1sD2F1lVShdoflDk97Y/iEJjZtX36HwCfCjNr3DrWLnBSMQ6hWULbkxRpW5Ay42CtAFUSoBdP7X",
	"NQ7wIwgbIZ6fnJ7MdQg8A0YyikP8+mR+8lpnJ6LWZj+z6kivwMhcb9YUitcxDuucYNbUlfatq18fchCb",
	"uoBNaEq1CuvaMoYlyROFw9O573j7zfDlUsKAHZ+Zj50S+NV8frACuJ8VPUWwnoT4ElkwiwCf2Qh8hqtI",
	"bW2tZ/+6x2x9O+ZpSsSm9Gucoieq1igjK8rMLs0ty6WH0rpKdX0GSHXB483BEOuXwUVb6/oSLXqUnR4s",
	"gNbF6WFLjyOXKCcky+KCCGLwZEgz4/YAzp5pXNSFbp81WyE71jon0RdKPWXmeuKjnpJuAT+EelmdG9TP",
	"pkDdRmbwRvcbpIEI/LnuCtSLxXcnSds2YDpor0C1cG2reWaLcnOF+hORGf++Ia8bj73zyEQkWZQR8WYc",
	"Y6ZMOAMsNV5wvo6nI9w0ntelne6aqVXi4nzBKnEROp3YaoIg2wX3VCMVEWpYMu/18Pd9rs0OXzBfBmJE",
	"kHsWaRzuZv80VgCWHcoxa8DOQ+LEZWC3l/Nw7aZ862JQNrrpisBZpNvEPBsh0k5YmP4/LltrfMSz035T",
	"9wDqQkICpO7WvgahG0j5IyCSJMi+cMSo0nYbqEfXvA92sZ3ufrdetnxe6X16qZ5Xj5mlhh4kRkRMJbJv",
	"CEbFp1OouIwSkZIbZGFrE7StuVmweJCaLTdG/YXuqHS0vxyMkGC/DUx3ESxYjH6yuP5cszDW47xwpPcQ",
	"/Lfod0qZN1qelsxnApYC5Ho4a9/YCf8fGtyO4QsSz0TEOcgr8sx9Yl+IZ7nUqD67Z/WiVT+N5KvzJGm+",
	"Z+9No/t/AEflcOttXUbfzFrzqbKWvthLsNGSC0SQJmEsdb14xL2fODzA63mNamba9+JB4Iui+C8AAP//",
	"FguH814jAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
