// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for GameStatus.
const (
	Active    GameStatus = "active"
	Cancelled GameStatus = "cancelled"
	Finished  GameStatus = "finished"
	Pending   GameStatus = "pending"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	case Finished:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for MyProblemStatus.
const (
	Archived  MyProblemStatus = "archived"
	Published MyProblemStatus = "published"
)

// Valid indicates whether the value is a known member of the MyProblemStatus enum.
func (e MyProblemStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for MyProblemVisibility.
const (
	MyProblemVisibilityPrivate  MyProblemVisibility = "private"
	MyProblemVisibilityPublic   MyProblemVisibility = "public"
	MyProblemVisibilityUnlisted MyProblemVisibility = "unlisted"
)

// Valid indicates whether the value is a known member of the MyProblemVisibility enum.
func (e MyProblemVisibility) Valid() bool {
	switch e {
	case MyProblemVisibilityPrivate:
		return true
	case MyProblemVisibilityPublic:
		return true
	case MyProblemVisibilityUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for PatchProblemRequestVisibility.
const (
	PatchProblemRequestVisibilityPrivate  PatchProblemRequestVisibility = "private"
	PatchProblemRequestVisibilityPublic   PatchProblemRequestVisibility = "public"
	PatchProblemRequestVisibilityUnlisted PatchProblemRequestVisibility = "unlisted"
)

// Valid indicates whether the value is a known member of the PatchProblemRequestVisibility enum.
func (e PatchProblemRequestVisibility) Valid() bool {
	switch e {
	case PatchProblemRequestVisibilityPrivate:
		return true
	case PatchProblemRequestVisibilityPublic:
		return true
	case PatchProblemRequestVisibilityUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for PatchProblemResponseVisibility.
const (
	Private  PatchProblemResponseVisibility = "private"
	Public   PatchProblemResponseVisibility = "public"
	Unlisted PatchProblemResponseVisibility = "unlisted"
)

// Valid indicates whether the value is a known member of the PatchProblemResponseVisibility enum.
func (e PatchProblemResponseVisibility) Valid() bool {
	switch e {
	case Private:
		return true
	case Public:
		return true
	case Unlisted:
		return true
	default:
		return false
	}
}

// Defines values for ProblemDifficulty.
const (
	Easy   ProblemDifficulty = "easy"
	Hard   ProblemDifficulty = "hard"
	Medium ProblemDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the ProblemDifficulty enum.
func (e ProblemDifficulty) Valid() bool {
	switch e {
	case Easy:
		return true
	case Hard:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// CompleteGameRequest defines model for CompleteGameRequest.
type CompleteGameRequest struct {
	WinnerId openapi_types.UUID `json:"winner_id"`
}

// ConfirmRequest defines model for ConfirmRequest.
type ConfirmRequest struct {
	Code  string `json:"code"`
	Email string `json:"email"`
}

// CreateGameRequest defines model for CreateGameRequest.
type CreateGameRequest struct {
	IsPublic         *bool    `json:"is_public,omitempty"`
	IsSolo           *bool    `json:"is_solo,omitempty"`
	ProblemIds       []string `json:"problem_ids"`
	TimeLimitMinutes *int     `json:"time_limit_minutes,omitempty"`
}

// DeletedResponse defines model for DeletedResponse.
type DeletedResponse struct {
	Deleted bool `json:"deleted"`
}

// EnterRequest defines model for EnterRequest.
type EnterRequest struct {
	Email string `json:"email"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

// ExecuteRequest defines model for ExecuteRequest.
type ExecuteRequest struct {
	Code     string `json:"code"`
	Input    string `json:"input"`
	Language string `json:"language"`
}

// ExecuteResponse defines model for ExecuteResponse.
type ExecuteResponse struct {
	ExitCode   int    `json:"exit_code"`
	Stderr     string `json:"stderr"`
	Stdout     string `json:"stdout"`
	TimeUsedMs int    `json:"time_used_ms"`
}

// Game defines model for Game.
type Game struct {
	CreatedAt        time.Time           `json:"created_at"`
	CreatorId        openapi_types.UUID  `json:"creator_id"`
	Id               int                 `json:"id"`
	InviteToken      *openapi_types.UUID `json:"invite_token,omitempty"`
	IsPublic         bool                `json:"is_public"`
	IsSolo           bool                `json:"is_solo"`
	Participants     []GameParticipant   `json:"participants"`
	ProblemIds       []string            `json:"problem_ids"`
	StartedAt        *time.Time          `json:"started_at,omitempty"`
	Status           GameStatus          `json:"status"`
	TimeLimitMinutes *int                `json:"time_limit_minutes,omitempty"`
	UpdatedAt        time.Time           `json:"updated_at"`
	WinnerId         *openapi_types.UUID `json:"winner_id,omitempty"`
}

// GameStatus defines model for Game.Status.
type GameStatus string

// GameParticipant defines model for GameParticipant.
type GameParticipant struct {
	Id   openapi_types.UUID `json:"id"`
	Name *string            `json:"name,omitempty"`
}

// GameResponse defines model for GameResponse.
type GameResponse struct {
	Game Game `json:"game"`
}

// GameSolution defines model for GameSolution.
type GameSolution struct {
	Code      string             `json:"code"`
	Language  string             `json:"language"`
	Name      *string            `json:"name,omitempty"`
	ProblemId string             `json:"problem_id"`
	SolvedAt  time.Time          `json:"solved_at"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// GameSolutionsResponse defines model for GameSolutionsResponse.
type GameSolutionsResponse struct {
	Solutions []GameSolution `json:"solutions"`
}

// ListGamesResponse defines model for ListGamesResponse.
type ListGamesResponse struct {
	Games []Game `json:"games"`
	Total int64  `json:"total"`
}

// ListMyProblemsResponse defines model for ListMyProblemsResponse.
type ListMyProblemsResponse struct {
	Problems []MyProblem `json:"problems"`
}

// ListProblemsResponse defines model for ListProblemsResponse.
type ListProblemsResponse struct {
	Problems []Problem `json:"problems"`
	Total    int64     `json:"total"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email  *string            `json:"email,omitempty"`
	Name   *string            `json:"name,omitempty"`
	UserId openapi_types.UUID `json:"user_id"`
}

// MyProblem defines model for MyProblem.
type MyProblem struct {
	Id         string              `json:"id"`
	Status     MyProblemStatus     `json:"status"`
	Title      string              `json:"title"`
	Version    *int                `json:"version,omitempty"`
	Visibility MyProblemVisibility `json:"visibility"`
}

// MyProblemStatus defines model for MyProblem.Status.
type MyProblemStatus string

// MyProblemVisibility defines model for MyProblem.Visibility.
type MyProblemVisibility string

// PatchProblemRequest defines model for PatchProblemRequest.
type PatchProblemRequest struct {
	Visibility PatchProblemRequestVisibility `json:"visibility"`
}

// PatchProblemRequestVisibility defines model for PatchProblemRequest.Visibility.
type PatchProblemRequestVisibility string

// PatchProblemResponse defines model for PatchProblemResponse.
type PatchProblemResponse struct {
	Slug       string                         `json:"slug"`
	Visibility PatchProblemResponseVisibility `json:"visibility"`
}

// PatchProblemResponseVisibility defines model for PatchProblemResponse.Visibility.
type PatchProblemResponseVisibility string

// Problem defines model for Problem.
type Problem struct {
	Description   string            `json:"description"`
	Difficulty    ProblemDifficulty `json:"difficulty"`
	Id            string            `json:"id"`
	MemoryLimitMb int               `json:"memory_limit_mb"`

	// TestCount Number of test cases
	TestCount   *int   `json:"test_count,omitempty"`
	TimeLimitMs int    `json:"time_limit_ms"`
	Title       string `json:"title"`
}

// ProblemDifficulty defines model for Problem.Difficulty.
type ProblemDifficulty string

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse struct {
	Problem Problem `json:"problem"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	Email     *string   `json:"email,omitempty"`
	ExpiresAt time.Time `json:"expires_at"`
	Name      *string   `json:"name,omitempty"`
	Token     string    `json:"token"`
	UserId    string    `json:"user_id"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	Name string `json:"name"`
}

// GameID defines model for GameID.
type GameID = int

// Error defines model for Error.
type Error = ErrorResponse

// ListGamesParams defines parameters for ListGames.
type ListGamesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListProblemsParams defines parameters for ListProblems.
type ListProblemsParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMyProblemsParams defines parameters for ListMyProblems.
type ListMyProblemsParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// PostAuthConfirmJSONRequestBody defines body for PostAuthConfirm for application/json ContentType.
type PostAuthConfirmJSONRequestBody = ConfirmRequest

// PostAuthEnterJSONRequestBody defines body for PostAuthEnter for application/json ContentType.
type PostAuthEnterJSONRequestBody = EnterRequest

// PatchAuthMeJSONRequestBody defines body for PatchAuthMe for application/json ContentType.
type PatchAuthMeJSONRequestBody = UpdateMeRequest

// PostExecuteJSONRequestBody defines body for PostExecute for application/json ContentType.
type PostExecuteJSONRequestBody = ExecuteRequest

// CreateGameJSONRequestBody defines body for CreateGame for application/json ContentType.
type CreateGameJSONRequestBody = CreateGameRequest

// CompleteGameJSONRequestBody defines body for CompleteGame for application/json ContentType.
type CompleteGameJSONRequestBody = CompleteGameRequest

// PatchProblemJSONRequestBody defines body for PatchProblem for application/json ContentType.
type PatchProblemJSONRequestBody = PatchProblemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Verify magic code and get session token
	// (POST /auth/confirm)
	PostAuthConfirm(w http.ResponseWriter, r *http.Request)
	// Request a magic code via email
	// (POST /auth/enter)
	PostAuthEnter(w http.ResponseWriter, r *http.Request)
	// End current session
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Get current authenticated user
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Update current user profile
	// (PATCH /auth/me)
	PatchAuthMe(w http.ResponseWriter, r *http.Request)
	// Execute code and return output
	// (POST /execute)
	PostExecute(w http.ResponseWriter, r *http.Request)
	// List games with pagination
	// (GET /games)
	ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams)
	// Create a new game
	// (POST /games)
	CreateGame(w http.ResponseWriter, r *http.Request)
	// Get game info by invite token (no join)
	// (GET /games/join/{invite_token})
	GetGameByToken(w http.ResponseWriter, r *http.Request, inviteToken openapi_types.UUID)
	// Join a game by invite token
	// (POST /games/join/{invite_token})
	JoinGameByToken(w http.ResponseWriter, r *http.Request, inviteToken openapi_types.UUID)
	// Delete game by ID
	// (DELETE /games/{id})
	DeleteGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Get game by ID
	// (GET /games/{id})
	GetGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Cancel a game
	// (POST /games/{id}/cancel)
	CancelGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Complete a game with a winner
	// (POST /games/{id}/complete)
	CompleteGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Leave a pending game as a participant
	// (POST /games/{id}/leave)
	LeaveGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Get passed solutions for a game
	// (GET /games/{id}/solutions)
	GetGameSolutions(w http.ResponseWriter, r *http.Request, id GameID)
	// Start a pending game
	// (POST /games/{id}/start)
	StartGame(w http.ResponseWriter, r *http.Request, id GameID)
	// Finish a solo game when the timer expires
	// (POST /games/{id}/timeout)
	TimeoutGame(w http.ResponseWriter, r *http.Request, id GameID)
	// List published public problems with optional search
	// (GET /problems)
	ListProblems(w http.ResponseWriter, r *http.Request, params ListProblemsParams)
	// List problems owned by the current user (all visibility)
	// (GET /problems/mine)
	ListMyProblems(w http.ResponseWriter, r *http.Request, params ListMyProblemsParams)
	// Get problem by slug (visibility check applied)
	// (GET /problems/{problem_id})
	GetProblem(w http.ResponseWriter, r *http.Request, problemId string)
	// Update problem visibility (owner only)
	// (PATCH /problems/{problem_id})
	PatchProblem(w http.ResponseWriter, r *http.Request, problemId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Verify magic code and get session token
// (POST /auth/confirm)
func (_ Unimplemented) PostAuthConfirm(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a magic code via email
// (POST /auth/enter)
func (_ Unimplemented) PostAuthEnter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End current session
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current authenticated user
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update current user profile
// (PATCH /auth/me)
func (_ Unimplemented) PatchAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Execute code and return output
// (POST /execute)
func (_ Unimplemented) PostExecute(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List games with pagination
// (GET /games)
func (_ Unimplemented) ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new game
// (POST /games)
func (_ Unimplemented) CreateGame(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game info by invite token (no join)
// (GET /games/join/{invite_token})
func (_ Unimplemented) GetGameByToken(w http.ResponseWriter, r *http.Request, inviteToken openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join a game by invite token
// (POST /games/join/{invite_token})
func (_ Unimplemented) JoinGameByToken(w http.ResponseWriter, r *http.Request, inviteToken openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete game by ID
// (DELETE /games/{id})
func (_ Unimplemented) DeleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get game by ID
// (GET /games/{id})
func (_ Unimplemented) GetGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a game
// (POST /games/{id}/cancel)
func (_ Unimplemented) CancelGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complete a game with a winner
// (POST /games/{id}/complete)
func (_ Unimplemented) CompleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Leave a pending game as a participant
// (POST /games/{id}/leave)
func (_ Unimplemented) LeaveGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get passed solutions for a game
// (GET /games/{id}/solutions)
func (_ Unimplemented) GetGameSolutions(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start a pending game
// (POST /games/{id}/start)
func (_ Unimplemented) StartGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Finish a solo game when the timer expires
// (POST /games/{id}/timeout)
func (_ Unimplemented) TimeoutGame(w http.ResponseWriter, r *http.Request, id GameID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List published public problems with optional search
// (GET /problems)
func (_ Unimplemented) ListProblems(w http.ResponseWriter, r *http.Request, params ListProblemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List problems owned by the current user (all visibility)
// (GET /problems/mine)
func (_ Unimplemented) ListMyProblems(w http.ResponseWriter, r *http.Request, params ListMyProblemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get problem by slug (visibility check applied)
// (GET /problems/{problem_id})
func (_ Unimplemented) GetProblem(w http.ResponseWriter, r *http.Request, problemId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update problem visibility (owner only)
// (PATCH /problems/{problem_id})
func (_ Unimplemented) PatchProblem(w http.ResponseWriter, r *http.Request, problemId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostAuthConfirm(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthConfirm(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthEnter operation middleware
func (siw *ServerInterfaceWrapper) PostAuthEnter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthEnter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAuthMe operation middleware
func (siw *ServerInterfaceWrapper) PatchAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExecute operation middleware
func (siw *ServerInterfaceWrapper) PostExecute(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExecute(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGames operation middleware
func (siw *ServerInterfaceWrapper) ListGames(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGamesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGames(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGame operation middleware
func (siw *ServerInterfaceWrapper) CreateGame(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGame(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameByToken operation middleware
func (siw *ServerInterfaceWrapper) GetGameByToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invite_token" -------------
	var inviteToken openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invite_token", chi.URLParam(r, "invite_token"), &inviteToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invite_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameByToken(w, r, inviteToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinGameByToken operation middleware
func (siw *ServerInterfaceWrapper) JoinGameByToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invite_token" -------------
	var inviteToken openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invite_token", chi.URLParam(r, "invite_token"), &inviteToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invite_token", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinGameByToken(w, r, inviteToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGame operation middleware
func (siw *ServerInterfaceWrapper) DeleteGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGame operation middleware
func (siw *ServerInterfaceWrapper) GetGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelGame operation middleware
func (siw *ServerInterfaceWrapper) CancelGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteGame operation middleware
func (siw *ServerInterfaceWrapper) CompleteGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeaveGame operation middleware
func (siw *ServerInterfaceWrapper) LeaveGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaveGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGameSolutions operation middleware
func (siw *ServerInterfaceWrapper) GetGameSolutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGameSolutions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGame operation middleware
func (siw *ServerInterfaceWrapper) StartGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TimeoutGame operation middleware
func (siw *ServerInterfaceWrapper) TimeoutGame(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GameID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TimeoutGame(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProblems operation middleware
func (siw *ServerInterfaceWrapper) ListProblems(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProblemsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProblems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyProblems operation middleware
func (siw *ServerInterfaceWrapper) ListMyProblems(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyProblemsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyProblems(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProblem operation middleware
func (siw *ServerInterfaceWrapper) GetProblem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "problem_id" -------------
	var problemId string

	err = runtime.BindStyledParameterWithOptions("simple", "problem_id", chi.URLParam(r, "problem_id"), &problemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "problem_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProblem(w, r, problemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchProblem operation middleware
func (siw *ServerInterfaceWrapper) PatchProblem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "problem_id" -------------
	var problemId string

	err = runtime.BindStyledParameterWithOptions("simple", "problem_id", chi.URLParam(r, "problem_id"), &problemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "problem_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchProblem(w, r, problemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/confirm", wrapper.PostAuthConfirm)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/enter", wrapper.PostAuthEnter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/auth/me", wrapper.PatchAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/execute", wrapper.PostExecute)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games", wrapper.ListGames)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games", wrapper.CreateGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games/join/{invite_token}", wrapper.GetGameByToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/join/{invite_token}", wrapper.JoinGameByToken)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/games/{id}", wrapper.DeleteGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games/{id}", wrapper.GetGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/cancel", wrapper.CancelGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/complete", wrapper.CompleteGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/leave", wrapper.LeaveGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/games/{id}/solutions", wrapper.GetGameSolutions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/start", wrapper.StartGame)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/games/{id}/timeout", wrapper.TimeoutGame)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems", wrapper.ListProblems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems/mine", wrapper.ListMyProblems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/problems/{problem_id}", wrapper.GetProblem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/problems/{problem_id}", wrapper.PatchProblem)
	})

	return r
}

type ErrorJSONResponse ErrorResponse

type PostAuthConfirmRequestObject struct {
	Body *PostAuthConfirmJSONRequestBody
}

type PostAuthConfirmResponseObject interface {
	VisitPostAuthConfirmResponse(w http.ResponseWriter) error
}

type PostAuthConfirm200JSONResponse TokenResponse

func (response PostAuthConfirm200JSONResponse) VisitPostAuthConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthConfirm400JSONResponse struct{ ErrorJSONResponse }

func (response PostAuthConfirm400JSONResponse) VisitPostAuthConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthConfirm404JSONResponse ErrorResponse

func (response PostAuthConfirm404JSONResponse) VisitPostAuthConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthConfirm429JSONResponse ErrorResponse

func (response PostAuthConfirm429JSONResponse) VisitPostAuthConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthEnterRequestObject struct {
	Body *PostAuthEnterJSONRequestBody
}

type PostAuthEnterResponseObject interface {
	VisitPostAuthEnterResponse(w http.ResponseWriter) error
}

type PostAuthEnter200JSONResponse StatusResponse

func (response PostAuthEnter200JSONResponse) VisitPostAuthEnterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthEnter400JSONResponse struct{ ErrorJSONResponse }

func (response PostAuthEnter400JSONResponse) VisitPostAuthEnterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLogoutRequestObject struct {
}

type PostAuthLogoutResponseObject interface {
	VisitPostAuthLogoutResponse(w http.ResponseWriter) error
}

type PostAuthLogout200JSONResponse StatusResponse

func (response PostAuthLogout200JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthLogout401JSONResponse struct{ ErrorJSONResponse }

func (response PostAuthLogout401JSONResponse) VisitPostAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse MeResponse

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMe401JSONResponse struct{ ErrorJSONResponse }

func (response GetAuthMe401JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchAuthMeRequestObject struct {
	Body *PatchAuthMeJSONRequestBody
}

type PatchAuthMeResponseObject interface {
	VisitPatchAuthMeResponse(w http.ResponseWriter) error
}

type PatchAuthMe200JSONResponse MeResponse

func (response PatchAuthMe200JSONResponse) VisitPatchAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchAuthMe400JSONResponse struct{ ErrorJSONResponse }

func (response PatchAuthMe400JSONResponse) VisitPatchAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchAuthMe401JSONResponse ErrorResponse

func (response PatchAuthMe401JSONResponse) VisitPatchAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostExecuteRequestObject struct {
	Body *PostExecuteJSONRequestBody
}

type PostExecuteResponseObject interface {
	VisitPostExecuteResponse(w http.ResponseWriter) error
}

type PostExecute200JSONResponse ExecuteResponse

func (response PostExecute200JSONResponse) VisitPostExecuteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostExecute400JSONResponse struct{ ErrorJSONResponse }

func (response PostExecute400JSONResponse) VisitPostExecuteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostExecute401JSONResponse ErrorResponse

func (response PostExecute401JSONResponse) VisitPostExecuteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGamesRequestObject struct {
	Params ListGamesParams
}

type ListGamesResponseObject interface {
	VisitListGamesResponse(w http.ResponseWriter) error
}

type ListGames200JSONResponse ListGamesResponse

func (response ListGames200JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGames400JSONResponse struct{ ErrorJSONResponse }

func (response ListGames400JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListGames401JSONResponse ErrorResponse

func (response ListGames401JSONResponse) VisitListGamesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateGameRequestObject struct {
	Body *CreateGameJSONRequestBody
}

type CreateGameResponseObject interface {
	VisitCreateGameResponse(w http.ResponseWriter) error
}

type CreateGame201JSONResponse GameResponse

func (response CreateGame201JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame400JSONResponse struct{ ErrorJSONResponse }

func (response CreateGame400JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGame401JSONResponse ErrorResponse

func (response CreateGame401JSONResponse) VisitCreateGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameByTokenRequestObject struct {
	InviteToken openapi_types.UUID `json:"invite_token"`
}

type GetGameByTokenResponseObject interface {
	VisitGetGameByTokenResponse(w http.ResponseWriter) error
}

type GetGameByToken200JSONResponse GameResponse

func (response GetGameByToken200JSONResponse) VisitGetGameByTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameByToken404JSONResponse struct{ ErrorJSONResponse }

func (response GetGameByToken404JSONResponse) VisitGetGameByTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type JoinGameByTokenRequestObject struct {
	InviteToken openapi_types.UUID `json:"invite_token"`
}

type JoinGameByTokenResponseObject interface {
	VisitJoinGameByTokenResponse(w http.ResponseWriter) error
}

type JoinGameByToken200JSONResponse GameResponse

func (response JoinGameByToken200JSONResponse) VisitJoinGameByTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type JoinGameByToken401JSONResponse struct{ ErrorJSONResponse }

func (response JoinGameByToken401JSONResponse) VisitJoinGameByTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type JoinGameByToken404JSONResponse ErrorResponse

func (response JoinGameByToken404JSONResponse) VisitJoinGameByTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type JoinGameByToken409JSONResponse ErrorResponse

func (response JoinGameByToken409JSONResponse) VisitJoinGameByTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGameRequestObject struct {
	Id GameID `json:"id"`
}

type DeleteGameResponseObject interface {
	VisitDeleteGameResponse(w http.ResponseWriter) error
}

type DeleteGame200JSONResponse DeletedResponse

func (response DeleteGame200JSONResponse) VisitDeleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGame401JSONResponse struct{ ErrorJSONResponse }

func (response DeleteGame401JSONResponse) VisitDeleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGame404JSONResponse ErrorResponse

func (response DeleteGame404JSONResponse) VisitDeleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetGameRequestObject struct {
	Id GameID `json:"id"`
}

type GetGameResponseObject interface {
	VisitGetGameResponse(w http.ResponseWriter) error
}

type GetGame200JSONResponse GameResponse

func (response GetGame200JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGame401JSONResponse struct{ ErrorJSONResponse }

func (response GetGame401JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGame403JSONResponse ErrorResponse

func (response GetGame403JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetGame404JSONResponse ErrorResponse

func (response GetGame404JSONResponse) VisitGetGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CancelGameRequestObject struct {
	Id GameID `json:"id"`
}

type CancelGameResponseObject interface {
	VisitCancelGameResponse(w http.ResponseWriter) error
}

type CancelGame200JSONResponse GameResponse

func (response CancelGame200JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CancelGame400JSONResponse struct{ ErrorJSONResponse }

func (response CancelGame400JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CancelGame401JSONResponse ErrorResponse

func (response CancelGame401JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CancelGame404JSONResponse ErrorResponse

func (response CancelGame404JSONResponse) VisitCancelGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGameRequestObject struct {
	Id   GameID `json:"id"`
	Body *CompleteGameJSONRequestBody
}

type CompleteGameResponseObject interface {
	VisitCompleteGameResponse(w http.ResponseWriter) error
}

type CompleteGame200JSONResponse GameResponse

func (response CompleteGame200JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGame400JSONResponse struct{ ErrorJSONResponse }

func (response CompleteGame400JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGame401JSONResponse ErrorResponse

func (response CompleteGame401JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CompleteGame404JSONResponse ErrorResponse

func (response CompleteGame404JSONResponse) VisitCompleteGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGameRequestObject struct {
	Id GameID `json:"id"`
}

type LeaveGameResponseObject interface {
	VisitLeaveGameResponse(w http.ResponseWriter) error
}

type LeaveGame200JSONResponse GameResponse

func (response LeaveGame200JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame401JSONResponse struct{ ErrorJSONResponse }

func (response LeaveGame401JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame403JSONResponse ErrorResponse

func (response LeaveGame403JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame404JSONResponse ErrorResponse

func (response LeaveGame404JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGame409JSONResponse ErrorResponse

func (response LeaveGame409JSONResponse) VisitLeaveGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetGameSolutionsRequestObject struct {
	Id GameID `json:"id"`
}

type GetGameSolutionsResponseObject interface {
	VisitGetGameSolutionsResponse(w http.ResponseWriter) error
}

type GetGameSolutions200JSONResponse GameSolutionsResponse

func (response GetGameSolutions200JSONResponse) VisitGetGameSolutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGameSolutions401JSONResponse struct{ ErrorJSONResponse }

func (response GetGameSolutions401JSONResponse) VisitGetGameSolutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGameSolutions403JSONResponse ErrorResponse

func (response GetGameSolutions403JSONResponse) VisitGetGameSolutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetGameSolutions404JSONResponse ErrorResponse

func (response GetGameSolutions404JSONResponse) VisitGetGameSolutionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type StartGameRequestObject struct {
	Id GameID `json:"id"`
}

type StartGameResponseObject interface {
	VisitStartGameResponse(w http.ResponseWriter) error
}

type StartGame200JSONResponse GameResponse

func (response StartGame200JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartGame400JSONResponse struct{ ErrorJSONResponse }

func (response StartGame400JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StartGame401JSONResponse ErrorResponse

func (response StartGame401JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StartGame404JSONResponse ErrorResponse

func (response StartGame404JSONResponse) VisitStartGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type TimeoutGameRequestObject struct {
	Id GameID `json:"id"`
}

type TimeoutGameResponseObject interface {
	VisitTimeoutGameResponse(w http.ResponseWriter) error
}

type TimeoutGame200JSONResponse GameResponse

func (response TimeoutGame200JSONResponse) VisitTimeoutGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TimeoutGame400JSONResponse struct{ ErrorJSONResponse }

func (response TimeoutGame400JSONResponse) VisitTimeoutGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type TimeoutGame401JSONResponse ErrorResponse

func (response TimeoutGame401JSONResponse) VisitTimeoutGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type TimeoutGame403JSONResponse ErrorResponse

func (response TimeoutGame403JSONResponse) VisitTimeoutGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type TimeoutGame404JSONResponse ErrorResponse

func (response TimeoutGame404JSONResponse) VisitTimeoutGameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListProblemsRequestObject struct {
	Params ListProblemsParams
}

type ListProblemsResponseObject interface {
	VisitListProblemsResponse(w http.ResponseWriter) error
}

type ListProblems200JSONResponse ListProblemsResponse

func (response ListProblems200JSONResponse) VisitListProblemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMyProblemsRequestObject struct {
	Params ListMyProblemsParams
}

type ListMyProblemsResponseObject interface {
	VisitListMyProblemsResponse(w http.ResponseWriter) error
}

type ListMyProblems200JSONResponse ListMyProblemsResponse

func (response ListMyProblems200JSONResponse) VisitListMyProblemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListMyProblems401JSONResponse struct{ ErrorJSONResponse }

func (response ListMyProblems401JSONResponse) VisitListMyProblemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProblemRequestObject struct {
	ProblemId string `json:"problem_id"`
}

type GetProblemResponseObject interface {
	VisitGetProblemResponse(w http.ResponseWriter) error
}

type GetProblem200JSONResponse ProblemResponse

func (response GetProblem200JSONResponse) VisitGetProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProblem404JSONResponse struct{ ErrorJSONResponse }

func (response GetProblem404JSONResponse) VisitGetProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchProblemRequestObject struct {
	ProblemId string `json:"problem_id"`
	Body      *PatchProblemJSONRequestBody
}

type PatchProblemResponseObject interface {
	VisitPatchProblemResponse(w http.ResponseWriter) error
}

type PatchProblem200JSONResponse PatchProblemResponse

func (response PatchProblem200JSONResponse) VisitPatchProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchProblem400JSONResponse struct{ ErrorJSONResponse }

func (response PatchProblem400JSONResponse) VisitPatchProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchProblem401JSONResponse ErrorResponse

func (response PatchProblem401JSONResponse) VisitPatchProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchProblem403JSONResponse ErrorResponse

func (response PatchProblem403JSONResponse) VisitPatchProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchProblem404JSONResponse ErrorResponse

func (response PatchProblem404JSONResponse) VisitPatchProblemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Verify magic code and get session token
	// (POST /auth/confirm)
	PostAuthConfirm(ctx context.Context, request PostAuthConfirmRequestObject) (PostAuthConfirmResponseObject, error)
	// Request a magic code via email
	// (POST /auth/enter)
	PostAuthEnter(ctx context.Context, request PostAuthEnterRequestObject) (PostAuthEnterResponseObject, error)
	// End current session
	// (POST /auth/logout)
	PostAuthLogout(ctx context.Context, request PostAuthLogoutRequestObject) (PostAuthLogoutResponseObject, error)
	// Get current authenticated user
	// (GET /auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// Update current user profile
	// (PATCH /auth/me)
	PatchAuthMe(ctx context.Context, request PatchAuthMeRequestObject) (PatchAuthMeResponseObject, error)
	// Execute code and return output
	// (POST /execute)
	PostExecute(ctx context.Context, request PostExecuteRequestObject) (PostExecuteResponseObject, error)
	// List games with pagination
	// (GET /games)
	ListGames(ctx context.Context, request ListGamesRequestObject) (ListGamesResponseObject, error)
	// Create a new game
	// (POST /games)
	CreateGame(ctx context.Context, request CreateGameRequestObject) (CreateGameResponseObject, error)
	// Get game info by invite token (no join)
	// (GET /games/join/{invite_token})
	GetGameByToken(ctx context.Context, request GetGameByTokenRequestObject) (GetGameByTokenResponseObject, error)
	// Join a game by invite token
	// (POST /games/join/{invite_token})
	JoinGameByToken(ctx context.Context, request JoinGameByTokenRequestObject) (JoinGameByTokenResponseObject, error)
	// Delete game by ID
	// (DELETE /games/{id})
	DeleteGame(ctx context.Context, request DeleteGameRequestObject) (DeleteGameResponseObject, error)
	// Get game by ID
	// (GET /games/{id})
	GetGame(ctx context.Context, request GetGameRequestObject) (GetGameResponseObject, error)
	// Cancel a game
	// (POST /games/{id}/cancel)
	CancelGame(ctx context.Context, request CancelGameRequestObject) (CancelGameResponseObject, error)
	// Complete a game with a winner
	// (POST /games/{id}/complete)
	CompleteGame(ctx context.Context, request CompleteGameRequestObject) (CompleteGameResponseObject, error)
	// Leave a pending game as a participant
	// (POST /games/{id}/leave)
	LeaveGame(ctx context.Context, request LeaveGameRequestObject) (LeaveGameResponseObject, error)
	// Get passed solutions for a game
	// (GET /games/{id}/solutions)
	GetGameSolutions(ctx context.Context, request GetGameSolutionsRequestObject) (GetGameSolutionsResponseObject, error)
	// Start a pending game
	// (POST /games/{id}/start)
	StartGame(ctx context.Context, request StartGameRequestObject) (StartGameResponseObject, error)
	// Finish a solo game when the timer expires
	// (POST /games/{id}/timeout)
	TimeoutGame(ctx context.Context, request TimeoutGameRequestObject) (TimeoutGameResponseObject, error)
	// List published public problems with optional search
	// (GET /problems)
	ListProblems(ctx context.Context, request ListProblemsRequestObject) (ListProblemsResponseObject, error)
	// List problems owned by the current user (all visibility)
	// (GET /problems/mine)
	ListMyProblems(ctx context.Context, request ListMyProblemsRequestObject) (ListMyProblemsResponseObject, error)
	// Get problem by slug (visibility check applied)
	// (GET /problems/{problem_id})
	GetProblem(ctx context.Context, request GetProblemRequestObject) (GetProblemResponseObject, error)
	// Update problem visibility (owner only)
	// (PATCH /problems/{problem_id})
	PatchProblem(ctx context.Context, request PatchProblemRequestObject) (PatchProblemResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostAuthConfirm operation middleware
func (sh *strictHandler) PostAuthConfirm(w http.ResponseWriter, r *http.Request) {
	var request PostAuthConfirmRequestObject

	var body PostAuthConfirmJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthConfirm(ctx, request.(PostAuthConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthConfirmResponseObject); ok {
		if err := validResponse.VisitPostAuthConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthEnter operation middleware
func (sh *strictHandler) PostAuthEnter(w http.ResponseWriter, r *http.Request) {
	var request PostAuthEnterRequestObject

	var body PostAuthEnterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthEnter(ctx, request.(PostAuthEnterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthEnter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthEnterResponseObject); ok {
		if err := validResponse.VisitPostAuthEnterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthLogout operation middleware
func (sh *strictHandler) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	var request PostAuthLogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthLogout(ctx, request.(PostAuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthLogoutResponseObject); ok {
		if err := validResponse.VisitPostAuthLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchAuthMe operation middleware
func (sh *strictHandler) PatchAuthMe(w http.ResponseWriter, r *http.Request) {
	var request PatchAuthMeRequestObject

	var body PatchAuthMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchAuthMe(ctx, request.(PatchAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchAuthMeResponseObject); ok {
		if err := validResponse.VisitPatchAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostExecute operation middleware
func (sh *strictHandler) PostExecute(w http.ResponseWriter, r *http.Request) {
	var request PostExecuteRequestObject

	var body PostExecuteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostExecute(ctx, request.(PostExecuteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostExecute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostExecuteResponseObject); ok {
		if err := validResponse.VisitPostExecuteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGames operation middleware
func (sh *strictHandler) ListGames(w http.ResponseWriter, r *http.Request, params ListGamesParams) {
	var request ListGamesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGames(ctx, request.(ListGamesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGames")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGamesResponseObject); ok {
		if err := validResponse.VisitListGamesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGame operation middleware
func (sh *strictHandler) CreateGame(w http.ResponseWriter, r *http.Request) {
	var request CreateGameRequestObject

	var body CreateGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGame(ctx, request.(CreateGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGameResponseObject); ok {
		if err := validResponse.VisitCreateGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameByToken operation middleware
func (sh *strictHandler) GetGameByToken(w http.ResponseWriter, r *http.Request, inviteToken openapi_types.UUID) {
	var request GetGameByTokenRequestObject

	request.InviteToken = inviteToken

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameByToken(ctx, request.(GetGameByTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameByToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameByTokenResponseObject); ok {
		if err := validResponse.VisitGetGameByTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinGameByToken operation middleware
func (sh *strictHandler) JoinGameByToken(w http.ResponseWriter, r *http.Request, inviteToken openapi_types.UUID) {
	var request JoinGameByTokenRequestObject

	request.InviteToken = inviteToken

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinGameByToken(ctx, request.(JoinGameByTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinGameByToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinGameByTokenResponseObject); ok {
		if err := validResponse.VisitJoinGameByTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteGame operation middleware
func (sh *strictHandler) DeleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request DeleteGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteGame(ctx, request.(DeleteGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteGameResponseObject); ok {
		if err := validResponse.VisitDeleteGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGame operation middleware
func (sh *strictHandler) GetGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request GetGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGame(ctx, request.(GetGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameResponseObject); ok {
		if err := validResponse.VisitGetGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelGame operation middleware
func (sh *strictHandler) CancelGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request CancelGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelGame(ctx, request.(CancelGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelGameResponseObject); ok {
		if err := validResponse.VisitCancelGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteGame operation middleware
func (sh *strictHandler) CompleteGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request CompleteGameRequestObject

	request.Id = id

	var body CompleteGameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteGame(ctx, request.(CompleteGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteGameResponseObject); ok {
		if err := validResponse.VisitCompleteGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaveGame operation middleware
func (sh *strictHandler) LeaveGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request LeaveGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveGame(ctx, request.(LeaveGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LeaveGameResponseObject); ok {
		if err := validResponse.VisitLeaveGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGameSolutions operation middleware
func (sh *strictHandler) GetGameSolutions(w http.ResponseWriter, r *http.Request, id GameID) {
	var request GetGameSolutionsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGameSolutions(ctx, request.(GetGameSolutionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGameSolutions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGameSolutionsResponseObject); ok {
		if err := validResponse.VisitGetGameSolutionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartGame operation middleware
func (sh *strictHandler) StartGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request StartGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartGame(ctx, request.(StartGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartGameResponseObject); ok {
		if err := validResponse.VisitStartGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TimeoutGame operation middleware
func (sh *strictHandler) TimeoutGame(w http.ResponseWriter, r *http.Request, id GameID) {
	var request TimeoutGameRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TimeoutGame(ctx, request.(TimeoutGameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TimeoutGame")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TimeoutGameResponseObject); ok {
		if err := validResponse.VisitTimeoutGameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProblems operation middleware
func (sh *strictHandler) ListProblems(w http.ResponseWriter, r *http.Request, params ListProblemsParams) {
	var request ListProblemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProblems(ctx, request.(ListProblemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProblems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProblemsResponseObject); ok {
		if err := validResponse.VisitListProblemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyProblems operation middleware
func (sh *strictHandler) ListMyProblems(w http.ResponseWriter, r *http.Request, params ListMyProblemsParams) {
	var request ListMyProblemsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyProblems(ctx, request.(ListMyProblemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyProblems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMyProblemsResponseObject); ok {
		if err := validResponse.VisitListMyProblemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProblem operation middleware
func (sh *strictHandler) GetProblem(w http.ResponseWriter, r *http.Request, problemId string) {
	var request GetProblemRequestObject

	request.ProblemId = problemId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProblem(ctx, request.(GetProblemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProblem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProblemResponseObject); ok {
		if err := validResponse.VisitGetProblemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchProblem operation middleware
func (sh *strictHandler) PatchProblem(w http.ResponseWriter, r *http.Request, problemId string) {
	var request PatchProblemRequestObject

	request.ProblemId = problemId

	var body PatchProblemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchProblem(ctx, request.(PatchProblemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchProblem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchProblemResponseObject); ok {
		if err := validResponse.VisitPatchProblemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rb3W/bOBL/VwjePbSAWjtN74D1W9N2gx6SbrDt3ksQGLQ0ttlKpEpSTtzA//uCH/qm",
	"JLu1sgn6FlnUcGZ+88Xh5B6HPEk5A6Yknt3jlAiSgAJhns5JAh/e6b8owzOcErXGAWYkATzDNMIBFvAt",
	"owIiPFMigwDLcA0J0V+obWpWMQUrEHi32+nVMuVMgiH+Xggu9B8hZwqY0n+SNI1pSBTlbPJFcqZ/K0n+",
	"W8ASz/C/JiXPE/tWTgy1Px19u1sEMhQ01cTwzG6HRLkiZ9Yw85YnaQwKtMR/wrcMpOEnFTwFoajl+JYy",
	"BmJOI/2w5CIhCs9wlhlNOHmlEpStsJU218115dObYilffIFQ4V2A33K2pCLp3DjkEVR0mu8RYEgIjT1v",
	"GrvbZYGl42VAABkQnsp5mi1iGuqHCJYki1WOuqO34DwGwjRBKueSx7y2dkli6V2cCr6IIZnTyOwEd0SD",
	"oRmfTk9eqFv+QmYJDvB0+urFkn7/vsi+f9diUAWJ9OolIXcf7MtX0wAnlLmnk2J7IgTZ6qWKJjCPaULV",
	"PKEsU1bahNzRJEvw7HRqCdinkwCzLI7JQrNXk72087rqq7L5NP8OtNlFheW29B7ZBRUxC801tspX+rZ5",
	"zxSITmwPMiMv+Zr3tenr1/Pcigt88fmby/fzj398nv/+x18f37WdKMAJSElWjc9WJAHEuEJLnrFh36vs",
	"XhL0SnEHYabgcDekLM2U901M2CpzAvRz6fgrPsip9jLaqfA7quYNdgsLDbBUEQjhZViqiHfIYjwlkxDN",
	"a17XZfmOUrFbUOGqQcwn47nJMi0ITKCK5kTVYnBEFLzQJH02ZL7he8btANPIrzTKNlTBXPGvwHyEOgJD",
	"hXA1gvaGTE+IJELRkKbE5eki9PXlRK3Cq/JDg2Ej+v2joVcqIgbAHFSqVERllnemI/Q1ToFF+mWASajo",
	"RlNZUkblGjRKIWEhxHEtTDZM/IjJIMBZGh1ssL11xoBGGk5oPqmCXHOHQn1V4ywtsWF2QdX7apJ1+W/V",
	"+NoFxX7uyFwcOFjuLqa6o+bKbTXkU63dzIdd+33icWZr0L3zSU/W2FshVdj9kZ7HmwMNM5M/WP7mH9aY",
	"Cjw5r2RqSJ2yG0eZLzkoUhY4tcJkM7EV5H08XlCpNDnZb2eH8eYL3YorEtegoEz99zUeLEnt9jmBLhku",
	"t1cWqh5BHJj7y1IQHVRyQbqLvxG46+TtJ5RdMNGn78u+Ui6vzQf9fe/A8NNu7JWhgLYj0u+TunUGcoma",
	"iHBNN515WsX+6LgBIV2wHU7OGyrpgsZUbVtc6DyYsZhKBTZs0Q1R4GHGl3AtezX6hbg+3V0RFa6d+jpP",
	"HyMwWyE5zFZntI2zlR+K4zNs9goG+e4yxFpHyMNxRJdLGmZxnWMgcmtOjhE1tfCaCL9VWjsvz6n1Etpz",
	"tk242Obl5sJ/6lAg9ZkpsxVUvaX1MUsWIBBfIr0KhUTauN4mUilrZcc+HR7VZ95VbmrKa+7YlrUHtsGA",
	"vncY94di796fjHP2GHkZqwp4+dfBgNnj85/1OfIYYR/uUipAHlTI7Z0qitNuXxLp14ElUeMz6M0kf5mD",
	"xWV3HybnPiF3F8BWao1nJ+5kVjwPIcP8JbtOSxBmgqrtJ21OdsMzIALEm0xTdg1pcz43P5f6XSuV2tYz",
	"ZUt7kLdehc+2CtAZUSoG9ObqA67kKTx9efJyquXmKTCSUjzDpy+nL0/N8UutDQMTkqn1JLRtYqMQbhWj",
	"1WLa5R8iPMNXXCrNpesnu/48SHXGo+3RWu2NbvWurlptSM1W/6vp9Gi71/3G0+jXCgCmNHWItF5f2919",
	"RAsu7f2BXf36kNWvftt7dcW28Oz6JsAySxIitniG/w+CLrcoISsaIn0qQoRFaAUKSZDaTpD1Ik3D2gIw",
	"BWLYEkzfdyQ7qPWUH9gKGvHaYwZvtRYl2LbXISbQA5MTFpEqUhtKkI3WJToxX7kuaj88F3bdP6qoC75a",
	"QYQ0H0ZTJz+oqXqYvL7Z1VT3nkUozIQAVth0RV82nq/Ao6pzMJq6hDG1VDmA+UzJ8a2T1pg6OgdV6IhU",
	"o1ixc6orco856Z8rWjq+rzdz8gO7ez8+lrmogs9hAX8cNC1XBaCaOZQKvqSxbSBOwN7i9EcJd9UzVgiv",
	"33g9MKrNayzfrb1ZohOgAJnF6vHA65gvs7UAlQmm42ia2UpyUjT6vJGt6BTaRnsxd3Htxi2+ZSC25byF",
	"OTvh6ohFcbN+MvX1ofxk+HIpoYOOj8zNiAbQ7pX68hOVSp9xrTIfDf6GLcMTuqVqjVKyoozkDWS/Q5dj",
	"FmOV5q05jr1c+uRoDNQuWDxg6vfIXSM9Hiyt2hBBDG4NphX3nXzhlE3uq7e/u75iRUt4tv3sDr0+v26M",
	"UVWvlfsGqoZatWM66l6w2mmMA49QPdW2LofMqIc+TaPFFllV2aMQesY40tA873a3/3HKfkk4tOAQOUs+",
	"zG0OPgBPfxvFJbUIiFj8G9BXnfOeRrtySqptAna8ykXcBvo+nsslEzf8OCqQzemvLtfKR7tGBfMQeCzj",
	"BTxaT0FvSHyU6j80rB2m+dNHgFMRQx1Idc+Z2GmY7hPIW/P+aeNXTvyMWm+Mh6EFwQXDNoRucrkHxMps",
	"88/BOEYvuT13/cCn0P2MyPH5dI3ICZDnVHNmIciOmrWMKgay6bGoC/36yUaFC1iqH66NTp9cJWXAQgS5",
	"uUgLP5H6l+psaMMCajNUfYm9mMd6tLbQnhjr6TKUcj/hjJ8SKSEqZUFLLrryhxnC7Xb1T/r10y4A3Jjx",
	"U43cBoGG/7ZQVDSB3hunz3bBEy/F3Ry3rmZziUdH9TE49e9GcES0S3OXwNfAkFqDUYRAbrrCGkZ18rGz",
	"9XxVTibu0X3+5u8YY98IzMH96/884f51aw61J7kUuPS1vcziYhLS/hUWn9rCjRvKJEYSiAjXddQnCWXQ",
	"C30523t08MdWt2csuUfh/JZVlD7yZUABEb9lLkatG/d/z0gco3J68XkDuPtyOr63x5xPuLXA65o99DQ6",
	"a4P4g//G+yD4NgcAPcC6JaP0mp1GNHAyzlboWQkUCtcQfkVGNIieD13Fd+JzZByOfx73TSI/8HncO3Xc",
	"Ywru/5B+jULADRXkplqx0Gc66gjEWWzCiiEqNrnhZSLGMzwhKcW7m93fAQAA///5JdQO9j8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
