// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Duels          string
	GooseDBVersion string
	Problems       string
	Solutions      string
	Users          string
}{
	Duels:          "duels",
	GooseDBVersion: "goose_db_version",
	Problems:       "problems",
	Solutions:      "solutions",
	Users:          "users",
}
