// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("DuelToUserUsingPlayer1", testDuelToOneUserUsingPlayer1)
	t.Run("DuelToUserUsingPlayer2", testDuelToOneUserUsingPlayer2)
	t.Run("DuelToProblemUsingProblem", testDuelToOneProblemUsingProblem)
	t.Run("DuelToUserUsingWinner", testDuelToOneUserUsingWinner)
	t.Run("SessionToUserUsingUser", testSessionToOneUserUsingUser)
	t.Run("SolutionToDuelUsingDuel", testSolutionToOneDuelUsingDuel)
	t.Run("SolutionToProblemUsingProblem", testSolutionToOneProblemUsingProblem)
	t.Run("SolutionToUserUsingUser", testSolutionToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("DuelToSolutions", testDuelToManySolutions)
	t.Run("ProblemToDuels", testProblemToManyDuels)
	t.Run("ProblemToSolutions", testProblemToManySolutions)
	t.Run("UserToPlayer1Duels", testUserToManyPlayer1Duels)
	t.Run("UserToPlayer2Duels", testUserToManyPlayer2Duels)
	t.Run("UserToWinnerDuels", testUserToManyWinnerDuels)
	t.Run("UserToSessions", testUserToManySessions)
	t.Run("UserToSolutions", testUserToManySolutions)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("DuelToUserUsingPlayer1Duels", testDuelToOneSetOpUserUsingPlayer1)
	t.Run("DuelToUserUsingPlayer2Duels", testDuelToOneSetOpUserUsingPlayer2)
	t.Run("DuelToProblemUsingDuels", testDuelToOneSetOpProblemUsingProblem)
	t.Run("DuelToUserUsingWinnerDuels", testDuelToOneSetOpUserUsingWinner)
	t.Run("SessionToUserUsingSessions", testSessionToOneSetOpUserUsingUser)
	t.Run("SolutionToDuelUsingSolutions", testSolutionToOneSetOpDuelUsingDuel)
	t.Run("SolutionToProblemUsingSolutions", testSolutionToOneSetOpProblemUsingProblem)
	t.Run("SolutionToUserUsingSolutions", testSolutionToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("DuelToUserUsingWinnerDuels", testDuelToOneRemoveOpUserUsingWinner)
	t.Run("SolutionToDuelUsingSolutions", testSolutionToOneRemoveOpDuelUsingDuel)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("DuelToSolutions", testDuelToManyAddOpSolutions)
	t.Run("ProblemToDuels", testProblemToManyAddOpDuels)
	t.Run("ProblemToSolutions", testProblemToManyAddOpSolutions)
	t.Run("UserToPlayer1Duels", testUserToManyAddOpPlayer1Duels)
	t.Run("UserToPlayer2Duels", testUserToManyAddOpPlayer2Duels)
	t.Run("UserToWinnerDuels", testUserToManyAddOpWinnerDuels)
	t.Run("UserToSessions", testUserToManyAddOpSessions)
	t.Run("UserToSolutions", testUserToManyAddOpSolutions)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("DuelToSolutions", testDuelToManySetOpSolutions)
	t.Run("UserToWinnerDuels", testUserToManySetOpWinnerDuels)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("DuelToSolutions", testDuelToManyRemoveOpSolutions)
	t.Run("UserToWinnerDuels", testUserToManyRemoveOpWinnerDuels)
}
