// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Duels     string
	Problems  string
	Solutions string
	Users     string
}{
	Duels:     "duels",
	Problems:  "problems",
	Solutions: "solutions",
	Users:     "users",
}
