// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDuels(t *testing.T) {
	t.Parallel()

	query := Duels()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDuelsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDuelsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Duels().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDuelsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DuelSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDuelsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DuelExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Duel exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DuelExists to return true, but got false.")
	}
}

func testDuelsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	duelFound, err := FindDuel(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if duelFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDuelsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Duels().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDuelsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Duels().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDuelsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	duelOne := &Duel{}
	duelTwo := &Duel{}
	if err = randomize.Struct(seed, duelOne, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}
	if err = randomize.Struct(seed, duelTwo, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = duelOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = duelTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Duels().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDuelsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	duelOne := &Duel{}
	duelTwo := &Duel{}
	if err = randomize.Struct(seed, duelOne, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}
	if err = randomize.Struct(seed, duelTwo, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = duelOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = duelTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func duelBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func duelAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
	*o = Duel{}
	return nil
}

func testDuelsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Duel{}
	o := &Duel{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, duelDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Duel object: %s", err)
	}

	AddDuelHook(boil.BeforeInsertHook, duelBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	duelBeforeInsertHooks = []DuelHook{}

	AddDuelHook(boil.AfterInsertHook, duelAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	duelAfterInsertHooks = []DuelHook{}

	AddDuelHook(boil.AfterSelectHook, duelAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	duelAfterSelectHooks = []DuelHook{}

	AddDuelHook(boil.BeforeUpdateHook, duelBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	duelBeforeUpdateHooks = []DuelHook{}

	AddDuelHook(boil.AfterUpdateHook, duelAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	duelAfterUpdateHooks = []DuelHook{}

	AddDuelHook(boil.BeforeDeleteHook, duelBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	duelBeforeDeleteHooks = []DuelHook{}

	AddDuelHook(boil.AfterDeleteHook, duelAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	duelAfterDeleteHooks = []DuelHook{}

	AddDuelHook(boil.BeforeUpsertHook, duelBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	duelBeforeUpsertHooks = []DuelHook{}

	AddDuelHook(boil.AfterUpsertHook, duelAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	duelAfterUpsertHooks = []DuelHook{}
}

func testDuelsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDuelsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDuelToManySolutions(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c Solution

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.DuelID, a.ID)
	queries.Assign(&c.DuelID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Solutions().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.DuelID, b.DuelID) {
			bFound = true
		}
		if queries.Equal(v.DuelID, c.DuelID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := DuelSlice{&a}
	if err = a.L.LoadSolutions(ctx, tx, false, (*[]*Duel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Solutions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Solutions = nil
	if err = a.L.LoadSolutions(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Solutions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testDuelToManyAddOpSolutions(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c, d, e Solution

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Solution{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Solution{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSolutions(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.DuelID) {
			t.Error("foreign key was wrong value", a.ID, first.DuelID)
		}
		if !queries.Equal(a.ID, second.DuelID) {
			t.Error("foreign key was wrong value", a.ID, second.DuelID)
		}

		if first.R.Duel != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Duel != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Solutions[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Solutions[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Solutions().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testDuelToManySetOpSolutions(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c, d, e Solution

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Solution{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetSolutions(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Solutions().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetSolutions(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Solutions().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DuelID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DuelID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.DuelID) {
		t.Error("foreign key was wrong value", a.ID, d.DuelID)
	}
	if !queries.Equal(a.ID, e.DuelID) {
		t.Error("foreign key was wrong value", a.ID, e.DuelID)
	}

	if b.R.Duel != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Duel != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Duel != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Duel != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Solutions[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Solutions[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testDuelToManyRemoveOpSolutions(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c, d, e Solution

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Solution{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddSolutions(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Solutions().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveSolutions(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Solutions().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DuelID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DuelID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Duel != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Duel != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Duel != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Duel != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Solutions) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Solutions[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Solutions[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testDuelToOneUserUsingPlayer1(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Duel
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.Player1ID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Player1().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := DuelSlice{&local}
	if err = local.L.LoadPlayer1(ctx, tx, false, (*[]*Duel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Player1 == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Player1 = nil
	if err = local.L.LoadPlayer1(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Player1 == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testDuelToOneUserUsingPlayer2(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Duel
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.Player2ID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Player2().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := DuelSlice{&local}
	if err = local.L.LoadPlayer2(ctx, tx, false, (*[]*Duel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Player2 == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Player2 = nil
	if err = local.L.LoadPlayer2(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Player2 == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testDuelToOneProblemUsingProblem(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Duel
	var foreign Problem

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, problemDBTypes, false, problemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Problem struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ProblemID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Problem().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddProblemHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Problem) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := DuelSlice{&local}
	if err = local.L.LoadProblem(ctx, tx, false, (*[]*Duel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Problem == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Problem = nil
	if err = local.L.LoadProblem(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Problem == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testDuelToOneUserUsingWinner(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Duel
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.WinnerID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Winner().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := DuelSlice{&local}
	if err = local.L.LoadWinner(ctx, tx, false, (*[]*Duel)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Winner == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Winner = nil
	if err = local.L.LoadWinner(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Winner == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testDuelToOneSetOpUserUsingPlayer1(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetPlayer1(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Player1 != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Player1Duels[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.Player1ID != x.ID {
			t.Error("foreign key was wrong value", a.Player1ID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Player1ID))
		reflect.Indirect(reflect.ValueOf(&a.Player1ID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.Player1ID != x.ID {
			t.Error("foreign key was wrong value", a.Player1ID, x.ID)
		}
	}
}
func testDuelToOneSetOpUserUsingPlayer2(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetPlayer2(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Player2 != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Player2Duels[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.Player2ID != x.ID {
			t.Error("foreign key was wrong value", a.Player2ID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Player2ID))
		reflect.Indirect(reflect.ValueOf(&a.Player2ID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.Player2ID != x.ID {
			t.Error("foreign key was wrong value", a.Player2ID, x.ID)
		}
	}
}
func testDuelToOneSetOpProblemUsingProblem(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c Problem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, problemDBTypes, false, strmangle.SetComplement(problemPrimaryKeyColumns, problemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, problemDBTypes, false, strmangle.SetComplement(problemPrimaryKeyColumns, problemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Problem{&b, &c} {
		err = a.SetProblem(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Problem != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Duels[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ProblemID != x.ID {
			t.Error("foreign key was wrong value", a.ProblemID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ProblemID))
		reflect.Indirect(reflect.ValueOf(&a.ProblemID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ProblemID != x.ID {
			t.Error("foreign key was wrong value", a.ProblemID, x.ID)
		}
	}
}
func testDuelToOneSetOpUserUsingWinner(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetWinner(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Winner != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.WinnerDuels[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.WinnerID, x.ID) {
			t.Error("foreign key was wrong value", a.WinnerID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WinnerID))
		reflect.Indirect(reflect.ValueOf(&a.WinnerID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.WinnerID, x.ID) {
			t.Error("foreign key was wrong value", a.WinnerID, x.ID)
		}
	}
}

func testDuelToOneRemoveOpUserUsingWinner(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Duel
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetWinner(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveWinner(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Winner().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Winner != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.WinnerID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.WinnerDuels) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testDuelsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDuelsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DuelSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDuelsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Duels().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	duelDBTypes = map[string]string{`ID`: `integer`, `Player1ID`: `integer`, `Player2ID`: `integer`, `ProblemID`: `integer`, `WinnerID`: `integer`, `Status`: `character varying`, `StartedAt`: `timestamp with time zone`, `CompletedAt`: `timestamp with time zone`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_           = bytes.MinRead
)

func testDuelsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(duelPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(duelAllColumns) == len(duelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, duelDBTypes, true, duelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDuelsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(duelAllColumns) == len(duelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Duel{}
	if err = randomize.Struct(seed, o, duelDBTypes, true, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, duelDBTypes, true, duelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(duelAllColumns, duelPrimaryKeyColumns) {
		fields = duelAllColumns
	} else {
		fields = strmangle.SetComplement(
			duelAllColumns,
			duelPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DuelSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDuelsUpsert(t *testing.T) {
	t.Parallel()

	if len(duelAllColumns) == len(duelPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Duel{}
	if err = randomize.Struct(seed, &o, duelDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Duel: %s", err)
	}

	count, err := Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, duelDBTypes, false, duelPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Duel: %s", err)
	}

	count, err = Duels().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
