// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Duels", testDuelsUpsert)

	t.Run("Problems", testProblemsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Sessions", testSessionsUpsert)

	t.Run("Solutions", testSolutionsUpsert)

	t.Run("Users", testUsersUpsert)
}
