// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSolutions(t *testing.T) {
	t.Parallel()

	query := Solutions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSolutionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSolutionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Solutions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSolutionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SolutionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSolutionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SolutionExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Solution exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SolutionExists to return true, but got false.")
	}
}

func testSolutionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	solutionFound, err := FindSolution(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if solutionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSolutionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Solutions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSolutionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Solutions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSolutionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	solutionOne := &Solution{}
	solutionTwo := &Solution{}
	if err = randomize.Struct(seed, solutionOne, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}
	if err = randomize.Struct(seed, solutionTwo, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = solutionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = solutionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Solutions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSolutionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	solutionOne := &Solution{}
	solutionTwo := &Solution{}
	if err = randomize.Struct(seed, solutionOne, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}
	if err = randomize.Struct(seed, solutionTwo, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = solutionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = solutionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func solutionBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func solutionAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Solution) error {
	*o = Solution{}
	return nil
}

func testSolutionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Solution{}
	o := &Solution{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, solutionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Solution object: %s", err)
	}

	AddSolutionHook(boil.BeforeInsertHook, solutionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	solutionBeforeInsertHooks = []SolutionHook{}

	AddSolutionHook(boil.AfterInsertHook, solutionAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	solutionAfterInsertHooks = []SolutionHook{}

	AddSolutionHook(boil.AfterSelectHook, solutionAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	solutionAfterSelectHooks = []SolutionHook{}

	AddSolutionHook(boil.BeforeUpdateHook, solutionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	solutionBeforeUpdateHooks = []SolutionHook{}

	AddSolutionHook(boil.AfterUpdateHook, solutionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	solutionAfterUpdateHooks = []SolutionHook{}

	AddSolutionHook(boil.BeforeDeleteHook, solutionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	solutionBeforeDeleteHooks = []SolutionHook{}

	AddSolutionHook(boil.AfterDeleteHook, solutionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	solutionAfterDeleteHooks = []SolutionHook{}

	AddSolutionHook(boil.BeforeUpsertHook, solutionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	solutionBeforeUpsertHooks = []SolutionHook{}

	AddSolutionHook(boil.AfterUpsertHook, solutionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	solutionAfterUpsertHooks = []SolutionHook{}
}

func testSolutionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSolutionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSolutionToOneDuelUsingDuel(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Solution
	var foreign Duel

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, duelDBTypes, false, duelColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Duel struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.DuelID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Duel().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddDuelHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Duel) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SolutionSlice{&local}
	if err = local.L.LoadDuel(ctx, tx, false, (*[]*Solution)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Duel == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Duel = nil
	if err = local.L.LoadDuel(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Duel == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSolutionToOneProblemUsingProblem(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Solution
	var foreign Problem

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, problemDBTypes, false, problemColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Problem struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ProblemID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Problem().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddProblemHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Problem) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SolutionSlice{&local}
	if err = local.L.LoadProblem(ctx, tx, false, (*[]*Solution)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Problem == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Problem = nil
	if err = local.L.LoadProblem(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Problem == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSolutionToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Solution
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, solutionDBTypes, false, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := SolutionSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Solution)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testSolutionToOneSetOpDuelUsingDuel(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Solution
	var b, c Duel

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Duel{&b, &c} {
		err = a.SetDuel(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Duel != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Solutions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.DuelID, x.ID) {
			t.Error("foreign key was wrong value", a.DuelID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DuelID))
		reflect.Indirect(reflect.ValueOf(&a.DuelID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.DuelID, x.ID) {
			t.Error("foreign key was wrong value", a.DuelID, x.ID)
		}
	}
}

func testSolutionToOneRemoveOpDuelUsingDuel(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Solution
	var b Duel

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, duelDBTypes, false, strmangle.SetComplement(duelPrimaryKeyColumns, duelColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetDuel(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveDuel(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Duel().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Duel != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.DuelID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Solutions) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSolutionToOneSetOpProblemUsingProblem(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Solution
	var b, c Problem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, problemDBTypes, false, strmangle.SetComplement(problemPrimaryKeyColumns, problemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, problemDBTypes, false, strmangle.SetComplement(problemPrimaryKeyColumns, problemColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Problem{&b, &c} {
		err = a.SetProblem(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Problem != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Solutions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ProblemID != x.ID {
			t.Error("foreign key was wrong value", a.ProblemID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ProblemID))
		reflect.Indirect(reflect.ValueOf(&a.ProblemID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ProblemID != x.ID {
			t.Error("foreign key was wrong value", a.ProblemID, x.ID)
		}
	}
}
func testSolutionToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Solution
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, solutionDBTypes, false, strmangle.SetComplement(solutionPrimaryKeyColumns, solutionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Solutions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testSolutionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSolutionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SolutionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSolutionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Solutions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	solutionDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `ProblemID`: `integer`, `DuelID`: `integer`, `Code`: `text`, `Language`: `character varying`, `Status`: `character varying`, `ExecutionTime`: `integer`, `MemoryUsed`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_               = bytes.MinRead
)

func testSolutionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(solutionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(solutionAllColumns) == len(solutionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSolutionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(solutionAllColumns) == len(solutionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Solution{}
	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, solutionDBTypes, true, solutionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(solutionAllColumns, solutionPrimaryKeyColumns) {
		fields = solutionAllColumns
	} else {
		fields = strmangle.SetComplement(
			solutionAllColumns,
			solutionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SolutionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSolutionsUpsert(t *testing.T) {
	t.Parallel()

	if len(solutionAllColumns) == len(solutionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Solution{}
	if err = randomize.Struct(seed, &o, solutionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Solution: %s", err)
	}

	count, err := Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, solutionDBTypes, false, solutionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Solution struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Solution: %s", err)
	}

	count, err = Solutions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
